import{beforeAll,afterAll,describe,expect,it}from'vitest';import{execFileSync}from'node:child_process';import fs from'node:fs';import path from'node:path';
const file=path.resolve(`data/test-contestant-${process.pid}.db`);let repo:any,db:any,episodeId='DEMO-EP-RUN',joins:any[]=[];
beforeAll(async()=>{execFileSync(process.execPath,['--import','tsx','server/db/migrate.ts'],{cwd:process.cwd(),env:{...process.env,DATABASE_PATH:file}});execFileSync(process.execPath,['--import','tsx','server/db/seed.ts'],{cwd:process.cwd(),env:{...process.env,DATABASE_PATH:file}});process.env.DATABASE_PATH=file;repo=await import('../server/contestantRepository.js');db=(await import('../server/db/database.js')).db;repo.openJoinSession(episodeId,{pin:'2468',maxParticipants:8});const code=repo.getJoinSession(episodeId).joinCode;for(const name of['Nova','Rune','Pixel','Comet'])joins.push(repo.joinContestant({joinCode:code,displayName:name,pin:'2468'},name))});afterAll(()=>{db.close();fs.unlinkSync(file)});
describe('contestant experience',()=>{
 it('uses generic errors, validates names and stores only token hashes',()=>{expect(()=>repo.joinContestant({joinCode:'BADCODE',displayName:'X'})).toThrow(/Unable to join/);expect(()=>repo.joinContestant({joinCode:repo.getJoinSession(episodeId).joinCode,displayName:'<script>',pin:'2468'})).toThrow();const raw=joins[0].token,row=db.prepare('SELECT token_hash FROM contestant_sessions WHERE display_name=?').get('Nova');expect(row.token_hash).not.toContain(raw);expect(row.token_hash).toMatch(/^[a-f0-9]{64}$/)});
 it('publishes a sanitized join graphic without internal episode identifiers',()=>{repo.showJoinGraphic(episodeId,'http://trivia.local/#play/old');const row=db.prepare("SELECT public_payload_json FROM graphic_overlays WHERE episode_id=? AND graphic_type='contestant-join' AND visible=1").get(episodeId)as any,text=JSON.parse(row.public_payload_json).text;expect(text).toContain(repo.getJoinSession(episodeId).joinCode);expect(text).not.toContain(episodeId);expect(text).not.toContain('pin')});
 it('toggles readiness only during a host ready check',()=>{expect(()=>repo.contestantReady(joins[0].token,true)).toThrow(/closed/);repo.setReadyCheck(episodeId,true,true);expect(repo.contestantReady(joins[0].token,true).ready).toBe(true);expect(repo.getHostContestantState(episodeId).contestants.find((x:any)=>x.displayName==='Nova').ready).toBe(true)});
 it('accepts exactly one authoritative winner and rejects late, stale and duplicate commands',()=>{const q:any=db.prepare("SELECT question_id FROM episode_questions WHERE episode_id=? AND state='unopened' LIMIT 1").get(episodeId);db.prepare("UPDATE episode_questions SET state='opened' WHERE episode_id=? AND question_id=?").run(episodeId,q.question_id);db.prepare("UPDATE episodes SET active_question_id=?,public_display_mode='question' WHERE id=?").run(q.question_id,episodeId);repo.armBuzzer(episodeId,'open');const b=repo.getHostContestantState(episodeId).buzzer,input=(i:number)=>({commandId:crypto.randomUUID(),buzzerSessionId:b.id,expectedRevision:b.revision,clientSequence:1,clientTimestamp:i===1?'1900-01-01T00:00:00Z':'2999-01-01T00:00:00Z'}),first=repo.buzz(joins[0].token,input(1)),late=repo.buzz(joins[1].token,input(2));expect(first.accepted).toBe(true);expect(late.accepted).toBe(false);expect(late.reason).toMatch(/stale|closed/);const command=input(3),once=repo.buzz(joins[2].token,command),twice=repo.buzz(joins[2].token,command);expect(once.accepted).toBe(false);expect(twice.duplicate).toBe(true);expect((db.prepare('SELECT count(*) n FROM buzz_attempts WHERE accepted=1').get()as any).n).toBe(1)});
 it('keeps the contestant projection sanitized',()=>{const text=JSON.stringify(repo.getContestantState(joins[1].token));for(const forbidden of['correctAnswer','alternateAnswers','hostNotes','source','token_hash','participantId','controllerConnected','prior_state_json','approximate_rtt_ms'])expect(text).not.toContain(forbidden)});
 it('adjudicates with server-computed XP, prevents double awards, and safely undoes',async()=>{const before=(db.prepare("SELECT score FROM episode_participants WHERE display_name='Nova'").get()as any).score,historyBefore=(db.prepare('SELECT count(*) n FROM buzz_attempts').get()as any).n;repo.adjudicate(episodeId,'correct');const after=(db.prepare("SELECT score FROM episode_participants WHERE display_name='Nova'").get()as any).score;expect(after-before).toBeGreaterThan(0);expect(()=>repo.adjudicate(episodeId,'correct')).toThrow();const live=await import('../server/liveRepository.js'),revision=(db.prepare('SELECT revision FROM episodes WHERE id=?').get(episodeId)as any).revision;live.executeLiveCommand({episodeId,commandId:crypto.randomUUID(),expectedRevision:revision,type:'action.undo',payload:{}});expect((db.prepare("SELECT score FROM episode_participants WHERE display_name='Nova'").get()as any).score).toBe(before);expect((db.prepare('SELECT count(*) n FROM buzz_attempts').get()as any).n).toBe(historyBefore);expect(repo.getHostContestantState(episodeId).buzzer.state).toBe('answering')});
 it('rotates reconnect tokens and revokes removed sessions immediately',()=>{const old=joins[3].token,next=repo.reconnectContestant(old);expect(()=>repo.getContestantState(old)).toThrow();expect(repo.getContestantState(next.token).displayName).toBe('Comet');const session=repo.getHostContestantState(episodeId).contestants.find((x:any)=>x.displayName==='Comet');repo.removeContestant(episodeId,session.sessionId);expect(()=>repo.getContestantState(next.token)).toThrow()});
 it('backs up contestant history without secrets and invalidates restored sessions',()=>{const backup=repo.exportContestantBackup(),serialized=JSON.stringify(backup);for(const join of joins)expect(serialized).not.toContain(join.token);expect(serialized).not.toContain('token_hash');expect(serialized).not.toContain('pin_hash');const attempts=(db.prepare('SELECT count(*) n FROM buzz_attempts').get()as any).n;repo.restoreContestantBackup(backup);expect((db.prepare('SELECT count(*) n FROM buzz_attempts').get()as any).n).toBe(attempts);expect((db.prepare("SELECT count(*) n FROM contestant_sessions WHERE status='removed'").get()as any).n).toBeGreaterThan(0);expect(()=>repo.getContestantState(joins[0].token)).toThrow()});
});
