import{describe,expect,it}from'vitest';import{EpisodeGenerationError,generateEpisode,rerollCategory,rerollQuestion}from'../shared/episodeGenerator.js';import{seededRandom}from'../shared/random.js';import type{EpisodeOptions,Question}from'../shared/types.js';
const opts=(over:Partial<EpisodeOptions>={}):EpisodeOptions=>({categoryCount:4,seed:'alpha',recentUsePolicy:{mode:'allow-all'},...over});
function library(categories=6,variants=2):Question[]{const out:Question[]=[];for(let c=1;c<=categories;c++)for(let d=1;d<=5;d++)for(let v=1;v<=variants;v++)out.push({id:`C${c}-D${d}-V${v}`,category:`Category ${c}`,subcategory:`Franchise ${c}`,difficulty:d as any,pointValue:d*100,questionText:`Question ${c}/${d}/${v}`,correctAnswer:'Answer',alternateAnswers:[],questionType:'text',mediaPath:null,hostNotes:'DEMO',source:'DEMO',active:true,usedCount:0,dateLastUsed:null,episodeLastUsed:null});return out}
const ids=(b:any)=>b.categories.flatMap((c:any)=>c.questions.map((q:any)=>q.id));
describe('episode generator',()=>{
 it('creates a 4×5 board with 20 unique questions',()=>{const b=generateEpisode(library(),opts());expect(b.categories).toHaveLength(4);expect(new Set(ids(b)).size).toBe(20)});
 it('creates a 5×5 board with 25 unique questions',()=>{const b=generateEpisode(library(),opts({categoryCount:5}));expect(new Set(ids(b)).size).toBe(25)});
 it('places levels 1–5 and 100–500 XP',()=>{for(const c of generateEpisode(library(),opts()).categories){expect(c.questions.map(q=>q.difficulty)).toEqual([1,2,3,4,5]);expect(c.questions.map(q=>q.pointValue)).toEqual([100,200,300,400,500])}});
 it('excludes inactive questions',()=>{const q=library();q.filter(x=>x.id.endsWith('V1')).forEach(x=>x.active=false);expect(ids(generateEpisode(q,opts())).every((x:string)=>x.endsWith('V2'))).toBe(true)});
 it('respects excluded categories and franchises',()=>{const b=generateEpisode(library(),opts({excludeCategories:['Category 1'],excludeFranchises:['Franchise 2']}));expect(b.categories.map(c=>c.name)).not.toContain('Category 1');expect(b.categories.map(c=>c.name)).not.toContain('Category 2')});
 it('respects never-used, episode, and day policies',()=>{const q=library();q.filter(x=>x.id.endsWith('V1')).forEach(x=>{x.usedCount=1;x.episodeLastUsed='E9';x.dateLastUsed='2026-07-12'});for(const p of [{mode:'never-used'},{mode:'last-episodes',count:2,recentEpisodeIds:['E9','E8']},{mode:'last-days',days:7,now:'2026-07-13'}] as EpisodeOptions['recentUsePolicy'][] )expect(ids(generateEpisode(q,opts({recentUsePolicy:p}))).every((x:string)=>x.endsWith('V2'))).toBe(true)});
 it('is repeatable by seed and can differ by seed',()=>{const q=library();expect(generateEpisode(q,opts())).toEqual(generateEpisode(q,opts()));expect(ids(generateEpisode(q,opts({seed:'one'})))).not.toEqual(ids(generateEpisode(q,opts({seed:'two'}))))});
 it('rerolls one question without changing other positions or adding duplicates',()=>{const q=library(),o=opts(),b=generateEpisode(q,o),before:string[]=ids(b),c=b.categories[0],used=new Set<string>(before);used.delete(c.questions[0].id);const changed=rerollQuestion(c,1,q,used,o,seededRandom('rq'));const after={...b,categories:[changed,...b.categories.slice(1)]};expect(ids(after).filter((_:string,i:number)=>i!==0)).toEqual(before.filter((_:string,i:number)=>i!==0));expect(new Set(ids(after)).size).toBe(20);expect(ids(after)[0]).not.toBe(before[0])});
 it('rerolls one category without changing others or adding duplicates',()=>{const q=library(),o=opts(),b=generateEpisode(q,o),after=rerollCategory(0,b,q,o,seededRandom('rc'));expect(after.categories.slice(1)).toEqual(b.categories.slice(1));expect(after.categories[0].name).not.toBe(b.categories[0].name);expect(new Set(ids(after)).size).toBe(20)});
 it('returns a useful error for insufficient inventory',()=>expect(()=>generateEpisode(library(3),opts())).toThrow(EpisodeGenerationError));
});
