import{beforeAll,afterAll,describe,expect,it}from'vitest';import{execFileSync}from'node:child_process';import path from'node:path';import type{EpisodeRecord,Question}from'../shared/types.js';
const dbPath=path.resolve(`data/test-lifecycle-${process.pid}.db`);let service:typeof import('../server/episodesRepository.js');let db:any;
const question=(c:number,d:number):Question=>({id:`LIFE-C${c}-D${d}`,category:`Lifecycle ${c}`,subcategory:'DEMO',difficulty:d as any,pointValue:d*100,questionText:`Lifecycle question ${c}/${d}`,correctAnswer:'Answer',alternateAnswers:[],questionType:'text',mediaPath:null,hostNotes:'TEST',source:'TEST',active:true,usedCount:0,dateLastUsed:null,episodeLastUsed:null});
const record=(id:string):EpisodeRecord=>({id,title:`Lifecycle ${id}`,episodeNumber:null,scheduledDate:'2026-07-13',status:'draft',seed:id,options:{categoryCount:4,seed:id,recentUsePolicy:{mode:'allow-all'}},categories:[1,2,3,4].map(c=>({name:`Lifecycle ${c}`,questions:[1,2,3,4,5].map(d=>question(c,d))}))});
beforeAll(async()=>{execFileSync(process.execPath,['--import','tsx','server/db/migrate.ts'],{cwd:process.cwd(),env:{...process.env,DATABASE_PATH:dbPath}});process.env.DATABASE_PATH=dbPath;service=await import('../server/episodesRepository.js');db=(await import('../server/db/database.js')).db;const add=db.prepare(`INSERT INTO questions(id,category,subcategory,difficulty,point_value,question_text,correct_answer,active,used_count) VALUES(?,?,?,?,?,?,?,1,0)`);for(let c=1;c<=4;c++)for(let d=1;d<=5;d++){const q=question(c,d);add.run(q.id,q.category,q.subcategory,q.difficulty,q.pointValue,q.questionText,q.correctAnswer)}});afterAll(()=>db.close());
describe('episode lifecycle persistence',()=>{
 it('lists, searches, filters, sorts, and reopens an unchanged draft board',()=>{service.saveEpisode(record('LIST'));const detail=service.getEpisode('LIST');expect(detail.categories.flatMap(c=>c.questions.map(q=>q.id))).toHaveLength(20);expect(service.listEpisodes({search:'Lifecycle LIST',status:'draft',sort:'created'}).items[0].id).toBe('LIST')});
 it('duplicates to a clean draft and preserves the original',()=>{service.saveEpisode(record('SOURCE'));service.transition('SOURCE','locked');service.startEpisode('SOURCE');service.addParticipant('SOURCE',{displayName:'Player'});const copy=service.duplicateEpisode('SOURCE');expect(copy.id).not.toBe('SOURCE');expect(copy.status).toBe('draft');expect(copy.sourceEpisodeId).toBe('SOURCE');expect(copy.participants).toHaveLength(0);expect(copy.categories).toEqual(service.getEpisode('SOURCE').categories);expect(service.getEpisode('SOURCE').status).toBe('in_progress')});
 it('deletes drafts transactionally and rejects non-draft deletion',()=>{service.saveEpisode(record('DELETE'));service.deleteDraft('DELETE');expect(()=>service.getEpisode('DELETE')).toThrow(/not found/i);service.saveEpisode(record('KEEP'));service.transition('KEEP','locked');expect(()=>service.deleteDraft('KEEP')).toThrow(/not allowed/i);expect((db.prepare("SELECT COUNT(*) n FROM questions").get()as any).n).toBe(20)});
 it('enforces transitions and records startedAt',()=>{service.saveEpisode(record('FLOW'));expect(()=>service.startEpisode('FLOW')).toThrow(/not allowed/i);service.transition('FLOW','locked');service.startEpisode('FLOW');expect(service.getEpisode('FLOW').startedAt).toBeTruthy();expect(()=>service.transition('FLOW','draft')).toThrow(/Cannot transition|not allowed/i)});
 it('persists participants, score deltas, question state, and prevents double scoring',()=>{service.saveEpisode(record('GAME'));service.transition('GAME','locked');service.startEpisode('GAME');let e=service.addParticipant('GAME',{displayName:'Ada'});const p=e.participants[0],qid=e.categories[0].questions[0].id;service.setQuestionState('GAME',qid,'opened');e=service.setQuestionState('GAME',qid,'completed',{participantId:p.id,awardPoints:100});expect(e.participants[0].score).toBe(100);expect(()=>service.setQuestionState('GAME',qid,'completed',{participantId:p.id,awardPoints:100})).toThrow(/finalized/);expect(()=>service.adjustScore('GAME',p.id,50,'')).toThrow(/reason/);expect(service.adjustScore('GAME',p.id,-25,'Correction').participants[0].score).toBe(75)});
 it('limits participants to eight',()=>{service.saveEpisode(record('EIGHT'));service.transition('EIGHT','locked');for(let i=1;i<=8;i++)service.addParticipant('EIGHT',{displayName:`P${i}`});expect(()=>service.addParticipant('EIGHT',{displayName:'P9'})).toThrow(/eight/)});
 it('completes atomically, calculates tied placements, and accounts usage exactly once',()=>{service.saveEpisode(record('COMPLETE'));service.transition('COMPLETE','locked');service.startEpisode('COMPLETE');let e=service.addParticipant('COMPLETE',{displayName:'Ada'});e=service.addParticipant('COMPLETE',{displayName:'Grace'});service.adjustScore('COMPLETE',e.participants[0].id,500,'Final score');service.adjustScore('COMPLETE',e.participants[1].id,500,'Final score');expect(()=>service.completeEpisode('COMPLETE')).toThrow(/unfinished/);e=service.completeEpisode('COMPLETE',true);expect(e.status).toBe('completed');expect(e.participants.map(p=>p.placement)).toEqual([1,1]);expect(e.finalWinner).toContain('Ada');const before=(db.prepare('SELECT SUM(used_count) n FROM questions').get()as any).n;service.completeEpisode('COMPLETE',true);const after=(db.prepare('SELECT SUM(used_count) n FROM questions').get()as any).n;expect(before).toBe(20);expect(after).toBe(20);expect((db.prepare("SELECT COUNT(*) n FROM questions WHERE episode_last_used='COMPLETE'").get()as any).n).toBe(20);expect(()=>service.adjustScore('COMPLETE',e.participants[0].id,1,'Late')).toThrow(/not allowed/i)});
 it('rolls back status and usage when any completion update fails',()=>{service.saveEpisode(record('ROLLBACK'));service.transition('ROLLBACK','locked');service.startEpisode('ROLLBACK');db.exec("CREATE TRIGGER fail_usage BEFORE UPDATE OF used_count ON questions WHEN NEW.id='LIFE-C1-D1' BEGIN SELECT RAISE(ABORT,'forced usage failure'); END");const before=(db.prepare('SELECT SUM(used_count) n FROM questions').get()as any).n;expect(()=>service.completeEpisode('ROLLBACK',true)).toThrow(/forced usage failure/);db.exec('DROP TRIGGER fail_usage');expect(service.getEpisode('ROLLBACK').status).toBe('in_progress');expect((db.prepare('SELECT SUM(used_count) n FROM questions').get()as any).n).toBe(before)});
 it('backs up all Phase 2 lifecycle data',()=>{const backup=service.exportAll();expect(backup.version).toBe(2);expect(backup.participants.length).toBeGreaterThan(0);expect(backup.gameActions.length).toBeGreaterThan(0)});
 it('restores a Phase 1-format backup into the Phase 2 schema',()=>{const q=db.prepare('SELECT * FROM questions').all();const e:any=db.prepare("SELECT * FROM episodes WHERE id='LIST'").get();const eq:any[]=db.prepare("SELECT * FROM episode_questions WHERE episode_id='LIST'").all();const oldEpisode={id:e.id,title:e.title,seed:e.seed,category_count:e.category_count,status:e.status,options_json:e.options_json,created_at:e.created_at,completed_at:e.completed_at,episode_number:e.episode_number,scheduled_date:e.scheduled_date,updated_at:e.updated_at};const oldQuestions=eq.map(r=>({episode_id:r.episode_id,question_id:r.question_id,category_position:r.category_position,difficulty:r.difficulty,completed:r.state==='completed'?1:0}));service.restoreAll({version:1,questions:q,episodes:[oldEpisode],episodeQuestions:oldQuestions,settings:[]});expect(service.getEpisode('LIST').gameplay).toHaveLength(20);expect(service.getEpisode('LIST').gameplay.every(g=>g.state==='unopened')).toBe(true)});
});
