import{afterAll,beforeAll,describe,expect,it}from'vitest';import{execFileSync}from'node:child_process';import path from'node:path';import type{EpisodeRecord,LiveCommand,Question}from'../shared/types.js';
const dbPath=path.resolve(`data/test-live-${process.pid}.db`);let episodes:typeof import('../server/episodesRepository.js'),live:typeof import('../server/liveRepository.js'),db:any,revision=0,participantId='';const id='LIVE';
const question=(c:number,d:number):Question=>({id:`LIVE-C${c}-D${d}`,category:`Live ${c}`,subcategory:'TEST',difficulty:d as any,pointValue:d*100,questionText:`Private question ${c}/${d}`,correctAnswer:`Secret ${c}/${d}`,alternateAnswers:['Alternate'],questionType:'text',mediaPath:null,hostNotes:'PRIVATE NOTE',source:'PRIVATE SOURCE',active:true,usedCount:0,dateLastUsed:null,episodeLastUsed:null});
const record:EpisodeRecord={id,title:'Live Test',episodeNumber:null,scheduledDate:null,status:'draft',seed:id,options:{categoryCount:4,seed:id,recentUsePolicy:{mode:'allow-all'}},categories:[1,2,3,4].map(c=>({name:`Live ${c}`,questions:[1,2,3,4,5].map(d=>question(c,d))}))};
const command=(type:LiveCommand['type'],payload:Record<string,unknown>={},commandId=crypto.randomUUID(),clock?:()=>Date)=>{const result=live.executeLiveCommand({episodeId:id,commandId,expectedRevision:revision,type,payload},clock);revision=result.revision;return result};
beforeAll(async()=>{execFileSync(process.execPath,['--import','tsx','server/db/migrate.ts'],{cwd:process.cwd(),env:{...process.env,DATABASE_PATH:dbPath}});process.env.DATABASE_PATH=dbPath;episodes=await import('../server/episodesRepository.js');live=await import('../server/liveRepository.js');db=(await import('../server/db/database.js')).db;const add=db.prepare(`INSERT INTO questions(id,category,subcategory,difficulty,point_value,question_text,correct_answer,alternate_answers,host_notes,source,active,used_count) VALUES(?,?,?,?,?,?,?,?,'PRIVATE NOTE','PRIVATE SOURCE',1,0)`);for(const c of record.categories)for(const q of c.questions)add.run(q.id,q.category,q.subcategory,q.difficulty,q.pointValue,q.questionText,q.correctAnswer,JSON.stringify(q.alternateAnswers));episodes.saveEpisode(record);episodes.transition(id,'locked');episodes.startEpisode(id);participantId=episodes.addParticipant(id,{displayName:'Team Delta'}).participants[0].id});afterAll(()=>db.close());
describe('Phase 3 live state',()=>{
 it('sanitizes every public mode and hides unopened content',()=>{const forbidden=['correctAnswer','correct_answer','alternateAnswers','alternate_answers','hostNotes','host_notes','source','actions','privateBoard','privateParticipants','control','questionId'];const inspect=(v:unknown)=>{if(Array.isArray(v))v.forEach(inspect);else if(v&&typeof v==='object'){for(const[k,x]of Object.entries(v)){expect(forbidden).not.toContain(k);inspect(x)}}};for(const mode of['standby','board','scores']as const){db.prepare('UPDATE episodes SET public_display_mode=? WHERE id=?').run(mode,id);const state=live.getPublicLiveState(id);inspect(state);expect(JSON.stringify(state)).not.toContain('Private question');expect(JSON.stringify(state)).not.toContain('Secret')}db.prepare("UPDATE episodes SET public_display_mode='standby' WHERE id=?").run(id)});
 it('selects privately and publishes only after explicit show',()=>{command('question.select',{questionId:'LIVE-C1-D1'});let pub=live.getPublicLiveState(id);expect(pub.question).toBeNull();expect(live.getPrivateLiveState(id,{role:'controller',controllerConnected:true,audienceCount:1}).activeQuestion?.correctAnswer).toBe('Secret 1/1');command('question.show');pub=live.getPublicLiveState(id);expect(pub.question?.text).toBe('Private question 1/1');expect(pub.question).not.toHaveProperty('answer')});
 it('reveals the answer only after an explicit command and can undo reveal',()=>{command('answer.reveal');expect(live.getPublicLiveState(id).question?.answer).toBe('Secret 1/1');command('action.undo');expect(live.getPublicLiveState(id).question).not.toHaveProperty('answer')});
 it('enforces idempotency and rejects stale revisions',()=>{const cid=crypto.randomUUID();const first=command('display.setMode',{mode:'board'},cid),before=revision;const duplicate=live.executeLiveCommand({episodeId:id,commandId:cid,expectedRevision:0,type:'display.setMode',payload:{mode:'scores'}});expect(duplicate.duplicate).toBe(true);expect(duplicate.revision).toBe(first.revision);expect(revision).toBe(before);expect(()=>live.executeLiveCommand({episodeId:id,commandId:crypto.randomUUID(),expectedRevision:0,type:'display.setMode',payload:{mode:'scores'}})).toThrow(/changed/i)});
 it('uses clock timestamps for start, pause, resume, adjustment, and expiry without revealing',()=>{let now=new Date('2026-01-01T00:00:00.000Z');const clock=()=>now;command('timer.start',{durationMs:10_000},crypto.randomUUID(),clock);now=new Date('2026-01-01T00:00:04.000Z');expect(live.getPublicLiveState(id,clock).timer.remainingMs).toBe(6000);command('timer.pause',{},crypto.randomUUID(),clock);expect(live.getPublicLiveState(id,clock).timer.status).toBe('paused');command('timer.adjust',{deltaMs:-1000},crypto.randomUUID(),clock);expect(live.getPublicLiveState(id,clock).timer.remainingMs).toBe(5000);command('timer.resume',{},crypto.randomUUID(),clock);now=new Date('2026-01-01T00:00:10.000Z');expect(live.expireTimers(clock)).toContain(id);const state=live.getPublicLiveState(id,clock);revision=state.revision;expect(state.timer.status).toBe('expired');expect(state.question).toBeNull()});
 it('persists score changes and undo with a compensating ledger row',()=>{command('score.adjust',{participantId,delta:300});expect(live.getPublicLiveState(id).participants[0].score).toBe(300);command('action.undo');expect(live.getPublicLiveState(id).participants[0].score).toBe(0);expect((db.prepare("SELECT COUNT(*) n FROM game_actions WHERE action_type='action_undone'").get()as any).n).toBeGreaterThan(0)});
 it('restores question state when the latest completion is undone',()=>{command('question.complete');expect(live.getPrivateLiveState(id,{role:'controller',controllerConnected:true,audienceCount:0}).activeQuestion?.state).toBe('completed');command('action.undo');expect(live.getPrivateLiveState(id,{role:'controller',controllerConnected:true,audienceCount:0}).activeQuestion?.state).toBe('opened')});
 it('keeps other episodes isolated',()=>{expect(()=>live.getPublicLiveState('MISSING')).toThrow(/not found/i);expect(live.getPublicLiveState(id).episodeId).toBe(id)});
});
