import{afterEach,beforeEach,describe,expect,it}from'vitest';import{DatabaseSync}from'node:sqlite';import fs from'node:fs';import path from'node:path';import{importQuestionCsv,questionInventory}from'../server/questionImport.js';
let db:DatabaseSync,file:string;const header='id,category,subcategory,difficulty,pointValue,questionText,correctAnswer,alternateAnswers,questionType,mediaPath,hostNotes,source,active,usedCount,dateLastUsed,episodeLastUsed';const row=(id:string,text:string,difficulty=1,extra='')=>`${id},Science,Space,${difficulty},999,${text},Answer,Alt one|Alt two,text,,,Source,true,0,,${extra}`;
beforeEach(()=>{file=path.resolve(`data/test-question-import-${process.pid}-${Math.random()}.db`);db=new DatabaseSync(file);db.exec(`CREATE TABLE questions(id TEXT PRIMARY KEY,category TEXT NOT NULL,subcategory TEXT NOT NULL,difficulty INTEGER NOT NULL CHECK(difficulty BETWEEN 1 AND 5),point_value INTEGER NOT NULL,question_text TEXT NOT NULL,correct_answer TEXT NOT NULL,alternate_answers TEXT NOT NULL CHECK(json_valid(alternate_answers)),question_type TEXT NOT NULL CHECK(question_type IN ('text','image','audio','video','multiple-choice')),media_path TEXT,host_notes TEXT NOT NULL,source TEXT NOT NULL,active INTEGER NOT NULL,used_count INTEGER NOT NULL,date_last_used TEXT,episode_last_used TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`)});afterEach(()=>{db.close();fs.unlinkSync(file)});
describe('production question import',()=>{
 it('rejects the full file for invalid rows and duplicate IDs without writing',()=>{const report=importQuestionCsv(db,[header,row('GOOD','A valid question'),row('GOOD','Another valid question',2),'BAD,,Space,9,900,,Answer,,text,,,Source,true,0,,'].join('\n'));expect(report.rejectedRows).toBeGreaterThan(0);expect(report.committed).toBe(false);expect((db.prepare('SELECT count(*) n FROM questions').get()as any).n).toBe(0)});
 it('detects exact text duplicates and warns about near duplicates',()=>{const exact=importQuestionCsv(db,[header,row('A','Who created the warp drive?'),row('B','Who created the warp drive?',2)].join('\n'));expect(exact.errors.join()).toContain('');expect(exact.errors.some(x=>x.issues.some(y=>y.includes('exact duplicate')))).toBe(true);const near=importQuestionCsv(db,[header,row('A','Who created the first warp drive?'),row('B','Who created first warp drive?',2)].join('\n'),{dryRun:true});expect(near.duplicateWarnings.length).toBeGreaterThan(0);expect((db.prepare('SELECT count(*) n FROM questions').get()as any).n).toBe(0)});
 it('imports atomically, derives XP, stores JSON alternates, and reports distribution',()=>{const report=importQuestionCsv(db,[header,row('A','Question one',1),row('B','Question two',2)].join('\n'));expect(report.committed).toBe(true);expect(report.categoryCounts).toEqual({Science:2});expect(report.difficultyCounts).toMatchObject({'1':1,'2':1});expect(report.distributionWarnings[0]).toMatch(/3, 4, 5/);const saved=db.prepare("SELECT point_value,alternate_answers FROM questions WHERE id='B'").get()as any;expect(saved.point_value).toBe(200);expect(JSON.parse(saved.alternate_answers)).toEqual(['Alt one','Alt two'])});
 it('skips without changing usage and only replaces usage when explicitly requested',()=>{db.prepare("INSERT INTO questions VALUES('KEEP','Old','',1,100,'Old text','A','[]','text',NULL,'','Source',1,7,'2025-01-01','EP-7',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run();let report=importQuestionCsv(db,[header,row('KEEP','Replacement text')].join('\n'),{skipExisting:true});expect(report.skippedRows).toBe(1);expect((db.prepare("SELECT used_count n FROM questions WHERE id='KEEP'").get()as any).n).toBe(7);report=importQuestionCsv(db,[header,row('KEEP','Replacement text')].join('\n'),{replaceExisting:true});expect(report.committed).toBe(true);const saved=db.prepare("SELECT used_count,date_last_used,question_text FROM questions WHERE id='KEEP'").get()as any;expect(saved.used_count).toBe(0);expect(saved.date_last_used).toBeNull();expect(saved.question_text).toBe('Replacement text')});
 it('deactivates missing questions and produces an active inventory matrix',()=>{db.prepare("INSERT INTO questions VALUES('OLD','Old', '',1,100,'Old unique text','A','[]','text',NULL,'','Source',1,0,NULL,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").run();const report=importQuestionCsv(db,[header,row('NEW','New unique text',3)].join('\n'),{deactivateMissing:true});expect(report.deactivatedRows).toBe(1);expect((db.prepare("SELECT active n FROM questions WHERE id='OLD'").get()as any).n).toBe(0);expect(questionInventory(db)).toMatchObject({total:1,rows:[{category:'Science',difficulty:3,count:1}]})});
});
