import crypto from 'node:crypto';
import { createServer } from 'node:http';
import express from 'express';
import Papa from 'papaparse';
import { ZodError } from 'zod';
import { generateEpisode,rerollCategory,rerollQuestion } from '../shared/episodeGenerator.js';
import { validateImportRows } from '../shared/importValidation.js';
import { seededRandom } from '../shared/random.js';
import { questionSchema } from '../shared/validation.js';
import { addParticipant,adjustScore,completeEpisode,deleteDraft,duplicateEpisode,exportAll,getEpisode,LifecycleError,listEpisodes,recentEpisodeIds,removeParticipant,renameParticipant,resetScores,restoreAll,saveEpisode,setQuestionState,startEpisode,transition } from './episodesRepository.js';
import { executeLiveCommand,getPrivateLiveState,getPublicLiveState } from './liveRepository.js';
import { attachLiveSockets } from './liveSocket.js';
import { executeD20Command,exportD20Backup,getD20History,getD20Settings,restoreD20Backup,saveD20Settings,saveEpisodeD20Settings } from './d20Repository.js';
import { createQuestion,deleteQuestion,duplicateQuestion,importQuestions,listQuestions,updateQuestion } from './questionsRepository.js';
import { assetFile,deleteAsset,deleteProfile,duplicateProfile,executePresentationCommand,exportPresentationBackup,listAssets,listProfiles,listThemes,restorePresentationBackup,saveAsset,saveProfile } from './presentationRepository.js';
import { db } from './db/database.js';
import './db/migrate.js';

const app=express();app.use(express.json({limit:'25mb'}));
const wrap=(fn:(q:any,r:any)=>unknown)=>(q:any,r:any,n:any)=>{try{Promise.resolve(fn(q,r)).catch(n)}catch(e){n(e)}};
const filters=(q:any)=>({search:String(q.search??''),category:String(q.category??''),subcategory:String(q.subcategory??''),difficulty:q.difficulty?Number(q.difficulty):undefined,active:q.active===''||q.active===undefined?undefined:q.active==='true',usage:q.usage||undefined});
const hydrate=(o:any)=>o.recentUsePolicy?.mode==='last-episodes'?{...o,recentUsePolicy:{...o.recentUsePolicy,recentEpisodeIds:recentEpisodeIds(o.recentUsePolicy.count)}}:o;

app.get('/api/health',(_q,r)=>r.json({ok:true}));
app.get('/api/questions',(q,r)=>r.json(listQuestions(filters(q.query))));
app.post('/api/questions',wrap((q,r)=>r.status(201).json(createQuestion(questionSchema.parse(q.body)))));
app.put('/api/questions/:id',wrap((q,r)=>r.json(updateQuestion(q.params.id,questionSchema.parse(q.body)))));
app.delete('/api/questions/:id',wrap((q,r)=>{if(!deleteQuestion(q.params.id))return r.status(404).json({error:'Question not found.'});r.status(204).end()}));
app.post('/api/questions/:id/duplicate',wrap((q,r)=>r.status(201).json(duplicateQuestion(q.params.id,String(q.body.id)))));
app.post('/api/questions/import',wrap((q,r)=>{const{questions,errors}=validateImportRows(q.body);if(errors.length)return r.status(422).json({error:'Import validation failed.',rows:errors});r.status(201).json({imported:importQuestions(questions)})}));
app.get('/api/questions/export.csv',(_q,r)=>r.type('text/csv').attachment('questions.csv').send(Papa.unparse(listQuestions().map(q=>({...q,alternateAnswers:q.alternateAnswers.join('|')})))));

app.post('/api/episodes/generate',wrap((q,r)=>{const seed=q.body.seed||crypto.randomUUID();r.json(generateEpisode(listQuestions(),hydrate({...q.body,seed})))}));
app.post('/api/episodes/reroll-question',wrap((q,r)=>{const used=new Set<string>(q.body.board.categories.flatMap((c:any)=>c.questions.map((x:any)=>x.id)));used.delete(q.body.category.questions.find((x:any)=>x.difficulty===q.body.difficulty)?.id);r.json(rerollQuestion(q.body.category,q.body.difficulty,listQuestions(),used,hydrate(q.body.options),seededRandom(q.body.rerollSeed)))}));
app.post('/api/episodes/reroll-category',wrap((q,r)=>r.json(rerollCategory(q.body.index,q.body.board,listQuestions(),hydrate(q.body.options),seededRandom(q.body.rerollSeed)))));
app.get('/api/episodes',wrap((q,r)=>r.json(listEpisodes({search:q.query.search,status:q.query.status,sort:q.query.sort,page:Number(q.query.page||1),pageSize:Number(q.query.pageSize||20)}))));
app.get('/api/episodes/:id',wrap((q,r)=>r.json(getEpisode(q.params.id))));
app.post('/api/episodes',wrap((q,r)=>r.status(201).json(saveEpisode({...q.body,status:'draft'}))));
app.put('/api/episodes/:id',wrap((q,r)=>r.json(saveEpisode({...q.body,id:q.params.id,status:'draft'}))));
app.post('/api/episodes/:id/duplicate',wrap((q,r)=>r.status(201).json(duplicateEpisode(q.params.id))));
app.delete('/api/episodes/:id',wrap((q,r)=>{deleteDraft(q.params.id);r.status(204).end()}));
for(const[name,to]of Object.entries({lock:'locked',unlock:'draft',archive:'archived',restore:'completed'}))app.post(`/api/episodes/:id/${name}`,wrap((q,r)=>r.json(transition(q.params.id,to as any))));
app.post('/api/episodes/:id/start',wrap((q,r)=>r.json(startEpisode(q.params.id))));
app.post('/api/episodes/:id/participants',wrap((q,r)=>r.status(201).json(addParticipant(q.params.id,q.body))));
app.put('/api/episodes/:id/participants/:participantId',wrap((q,r)=>r.json(renameParticipant(q.params.id,q.params.participantId,q.body.displayName))));
app.delete('/api/episodes/:id/participants/:participantId',wrap((q,r)=>r.json(removeParticipant(q.params.id,q.params.participantId))));
app.post('/api/episodes/:id/questions/:questionId/open',wrap((q,r)=>r.json(setQuestionState(q.params.id,q.params.questionId,'opened'))));
app.post('/api/episodes/:id/questions/:questionId/complete',wrap((q,r)=>r.json(setQuestionState(q.params.id,q.params.questionId,'completed',q.body))));
app.post('/api/episodes/:id/questions/:questionId/skip',wrap((q,r)=>r.json(setQuestionState(q.params.id,q.params.questionId,'skipped',q.body))));
app.post('/api/episodes/:id/scores/:participantId/adjust',wrap((q,r)=>r.json(adjustScore(q.params.id,q.params.participantId,Number(q.body.delta),q.body.reason))));
app.post('/api/episodes/:id/scores/reset',wrap((q,r)=>r.json(resetScores(q.params.id))));
app.post('/api/episodes/:id/complete',wrap((q,r)=>r.json(completeEpisode(q.params.id,Boolean(q.body.confirmIncomplete)))));

app.get('/api/live/:id/public',wrap((q,r)=>r.json(getPublicLiveState(q.params.id))));
app.get('/api/live/:id/private',wrap((q,r)=>r.json(getPrivateLiveState(q.params.id,{role:'observer',controllerConnected:false,audienceCount:0}))));
app.post('/api/live/:id/commands',wrap((q,r)=>{const command={...q.body,episodeId:q.params.id};const result=String(command.type).startsWith('d20.')?executeD20Command(command):String(command.type).startsWith('presentation.')?executePresentationCommand(command):executeLiveCommand(command);live.broadcast(q.params.id);r.json(result)}));
app.post('/api/live/:id/complete',wrap((q,r)=>{completeEpisode(q.params.id,Boolean(q.body.confirmIncomplete));db.prepare("UPDATE episodes SET public_display_mode='final',revision=revision+1 WHERE id=?").run(q.params.id);live.broadcast(q.params.id);r.json(getPublicLiveState(q.params.id))}));
app.post('/api/live/:id/participants',wrap((q,r)=>{addParticipant(q.params.id,q.body);db.prepare('UPDATE episodes SET revision=revision+1 WHERE id=?').run(q.params.id);live.broadcast(q.params.id);r.status(201).json({ok:true})}));
app.get('/api/settings/d20',wrap((_q,r)=>r.json(getD20Settings())));app.put('/api/settings/d20',wrap((q,r)=>r.json(saveD20Settings(q.body))));
app.get('/api/episodes/:id/d20',wrap((q,r)=>r.json(getD20Settings(q.params.id))));app.put('/api/episodes/:id/d20',wrap((q,r)=>r.json(saveEpisodeD20Settings(q.params.id,q.body))));app.get('/api/episodes/:id/d20/rolls',wrap((q,r)=>r.json(getD20History(q.params.id))));
app.get('/api/presentation/themes',wrap((_q,r)=>r.json(listThemes())));
app.get('/api/presentation/profiles',wrap((_q,r)=>r.json(listProfiles())));
app.post('/api/presentation/profiles',wrap((q,r)=>r.status(201).json(saveProfile(q.body))));
app.post('/api/presentation/profiles/:id/duplicate',wrap((q,r)=>r.status(201).json(duplicateProfile(q.params.id))));
app.delete('/api/presentation/profiles/:id',wrap((q,r)=>{deleteProfile(q.params.id);r.status(204).end()}));
app.get('/api/presentation/assets',wrap((_q,r)=>r.json(listAssets())));
app.post('/api/presentation/assets',wrap((q,r)=>r.status(201).json(saveAsset(q.body))));
app.get('/api/presentation/assets/:id',wrap((q,r)=>{const asset=assetFile(q.params.id);if(!asset)return r.status(404).end();r.type(asset.mime).set('Cache-Control','public, max-age=31536000, immutable').sendFile(asset.file)}));
app.delete('/api/presentation/assets/:id',wrap((q,r)=>{deleteAsset(q.params.id,q.query.force==='true');r.status(204).end()}));
app.get('/api/backup',(_q,r)=>r.attachment('geek-trivia-backup.json').json({...exportAll(),d20:exportD20Backup(),presentation:exportPresentationBackup()}));
app.post('/api/restore',wrap((q,r)=>{const d20=q.body?.d20,presentation=q.body?.presentation;restoreAll(q.body);restoreD20Backup(d20);restorePresentationBackup(presentation);r.json({restored:true})}));
app.use((error:any,_q:any,r:any,_n:any)=>{const duplicate=String(error?.message).includes('UNIQUE constraint failed: questions.id');const status=error instanceof LifecycleError?(error.code==='EPISODE_NOT_FOUND'?404:409):duplicate?409:400;r.status(status).json({error:duplicate?'A question with that ID already exists.':error instanceof ZodError?error.issues.map(x=>`${x.path.join('.')}: ${x.message}`).join('; '):error?.message??'Unexpected error.',code:error?.code,details:error?.details})});

const server=createServer(app),live=attachLiveSockets(server);
server.listen(8787,()=>console.log('Geek Trivia Live API: http://localhost:8787'));
export{app,server};
