import crypto from 'node:crypto';
import { z } from 'zod';
import type { LiveCommand, PrivateLiveState, PublicDisplayMode, PublicLiveState, TimerStatus } from '../shared/types.js';
import { db, rowToQuestion } from './db/database.js';
import { LifecycleError } from './episodesRepository.js';
import { getD20History,getD20Settings,getPrivateD20,getPublicD20,scoreActiveQuestion } from './d20Repository.js';

export type Clock=()=>Date;
const commandSchema=z.object({
  episodeId:z.string().min(1).max(100),commandId:z.string().min(8).max(100),expectedRevision:z.number().int().nonnegative(),
  type:z.enum(['question.select','question.show','answer.reveal','question.complete','question.skip','score.adjust','score.question','timer.start','timer.pause','timer.resume','timer.reset','timer.adjust','display.setMode','action.undo']),
  payload:z.record(z.string(),z.unknown()).default({})
});
const modes:PublicDisplayMode[]=['standby','board','question','answer','scores','final'];
const reversible=new Set(['question_selected','question_shown','answer_revealed','question_completed','question_skipped','score_adjusted','question_scored','timer_started','timer_paused','timer_resumed','timer_reset','timer_adjusted','display_mode_changed']);
const nowIso=(clock:Clock)=>clock().toISOString();
const episode=(id:string):any=>{const row=db.prepare('SELECT * FROM episodes WHERE id=?').get(id);if(!row)throw new LifecycleError('EPISODE_NOT_FOUND','Episode not found.');return row};

function effectiveTimer(e:any,clock:Clock){
  let remaining=Number(e.timer_remaining_ms),status=e.timer_status as TimerStatus;
  if(status==='running'&&e.timer_resumed_at){remaining=Math.max(0,remaining-(clock().getTime()-Date.parse(e.timer_resumed_at)));if(!remaining)status='expired'}
  return{durationMs:e.timer_duration_ms,remainingMs:remaining,status,resumedAt:e.timer_resumed_at,expiredAt:status==='expired'?(e.timer_expired_at??nowIso(clock)):null,serverNow:nowIso(clock)};
}
function categories(id:string){return db.prepare(`SELECT eq.question_id,eq.category_position,eq.difficulty,eq.state,q.category,q.question_text,q.correct_answer,q.alternate_answers,q.host_notes,q.source
  FROM episode_questions eq JOIN questions q ON q.id=eq.question_id WHERE eq.episode_id=? ORDER BY eq.category_position,eq.difficulty`).all(id) as any[]}
function activeRow(e:any,rows:any[]){return rows.find(r=>r.question_id===e.active_question_id)??null}

export function getPublicLiveState(id:string,clock:Clock=()=>new Date()):PublicLiveState{
  const e=episode(id),rows=categories(id),active=activeRow(e,rows),visible=active&&['question','answer'].includes(e.public_display_mode);
  const board=[...new Set(rows.map(r=>r.category_position))].map(position=>{const group=rows.filter(r=>r.category_position===position);return{name:group[0]?.category??'',squares:group.map(r=>({key:`${r.category_position}-${r.difficulty}`,value:r.difficulty*100,status:r.state,active:r.question_id===e.active_question_id}))}});
  const participants=(db.prepare('SELECT display_name,color,score,placement FROM episode_participants WHERE episode_id=? ORDER BY score DESC,created_at').all(id)as any[]).map(p=>({displayName:p.display_name,color:p.color,score:p.score,placement:p.placement}));
  return{episodeId:id,title:e.title,status:e.status,revision:e.revision,mode:e.public_display_mode,board,question:visible?{category:active.category,value:active.difficulty*100,text:active.question_text,...(e.answer_revealed&&e.public_display_mode==='answer'?{answer:active.correct_answer}:{})}:null,timer:effectiveTimer(e,clock),participants,message:null,d20:getPublicD20(id)};
}
function undoInfo(id:string){
  const row:any=db.prepare(`SELECT * FROM game_actions WHERE episode_id=? AND prior_state_json IS NOT NULL AND undone_at IS NULL ORDER BY rowid DESC LIMIT 1`).get(id);
  if(!row)return null;const e=episode(id);const safe=e.status==='in_progress'&&reversible.has(row.action_type);return{actionId:row.id,description:describe(row),safe,reason:safe?undefined:'Only the latest live action in an in-progress episode can be undone.'};
}
function describe(a:any){const names:Record<string,string>={score_adjusted:'score change',question_scored:'score change',question_completed:'question completion',question_skipped:'question skip',answer_revealed:'answer reveal',display_mode_changed:'display change',timer_started:'timer start',timer_paused:'timer pause',timer_resumed:'timer resume',timer_reset:'timer reset',timer_adjusted:'timer adjustment',question_selected:'question selection',question_shown:'question reveal'};return`Undo: ${names[a.action_type]??a.action_type}`}
export function getPrivateLiveState(id:string,control:PrivateLiveState['control'],clock:Clock=()=>new Date()):PrivateLiveState{
  const pub=getPublicLiveState(id,clock),e=episode(id),rows=categories(id),a=activeRow(e,rows);
  const privateBoard=[...new Set(rows.map(r=>r.category_position))].map(position=>{const group=rows.filter(r=>r.category_position===position);return{name:group[0]?.category??'',squares:group.map(r=>({id:r.question_id,value:r.difficulty*100,status:r.state,active:r.question_id===e.active_question_id}))}});
  const privateParticipants=(db.prepare('SELECT id,display_name,color,score,placement FROM episode_participants WHERE episode_id=? ORDER BY score DESC,created_at').all(id)as any[]).map(p=>({id:p.id,displayName:p.display_name,color:p.color,score:p.score,placement:p.placement}));
  const actions=(db.prepare('SELECT * FROM game_actions WHERE episode_id=? ORDER BY rowid DESC LIMIT 30').all(id)as any[]).map(r=>({id:r.id,episodeId:r.episode_id,actionType:r.action_type,createdAt:r.created_at,questionId:r.question_id,participantId:r.participant_id,pointDelta:r.point_delta,reason:r.reason,metadata:JSON.parse(r.metadata_json||'{}')}));
  const hasActiveD20Modifier=Boolean(db.prepare("SELECT 1 FROM episode_questions WHERE episode_id=? AND modifier_status='active' LIMIT 1").get(id));
  return{...pub,privateBoard,privateParticipants,activeQuestion:a?{id:a.question_id,category:a.category,value:a.difficulty*100,text:a.question_text,correctAnswer:a.correct_answer,alternateAnswers:JSON.parse(a.alternate_answers),hostNotes:a.host_notes,source:a.source,state:a.state}:null,actions,control,undo:undoInfo(id),d20Private:getPrivateD20(id),d20Settings:getD20Settings(id),d20History:getD20History(id),hasActiveD20Modifier};
}
function snapshot(id:string){const e:any=episode(id);return{episode:{public_display_mode:e.public_display_mode,active_question_id:e.active_question_id,answer_revealed:e.answer_revealed,timer_duration_ms:e.timer_duration_ms,timer_remaining_ms:e.timer_remaining_ms,timer_status:e.timer_status,timer_resumed_at:e.timer_resumed_at,timer_expired_at:e.timer_expired_at},participants:db.prepare('SELECT id,score FROM episode_participants WHERE episode_id=?').all(id),questions:db.prepare('SELECT question_id,state,opened_at,completed_at,outcome,awarded_participant_id,awarded_points,notes,modifier_status FROM episode_questions WHERE episode_id=?').all(id)} }
function restore(id:string,s:any){const e=s.episode;db.prepare(`UPDATE episodes SET public_display_mode=?,active_question_id=?,answer_revealed=?,timer_duration_ms=?,timer_remaining_ms=?,timer_status=?,timer_resumed_at=?,timer_expired_at=? WHERE id=?`).run(e.public_display_mode,e.active_question_id,e.answer_revealed,e.timer_duration_ms,e.timer_remaining_ms,e.timer_status,e.timer_resumed_at,e.timer_expired_at,id);for(const p of s.participants)db.prepare('UPDATE episode_participants SET score=? WHERE id=? AND episode_id=?').run(p.score,p.id,id);for(const q of s.questions)db.prepare(`UPDATE episode_questions SET state=?,opened_at=?,completed_at=?,outcome=?,awarded_participant_id=?,awarded_points=?,notes=?,modifier_status=? WHERE episode_id=? AND question_id=?`).run(q.state,q.opened_at,q.completed_at,q.outcome,q.awarded_participant_id,q.awarded_points,q.notes,q.modifier_status??null,id,q.question_id)}
function record(id:string,type:string,prior:any,result:any,data:Partial<{qid:string;pid:string;delta:number;reason:string;reverses:string}>={}){const aid=crypto.randomUUID();db.prepare(`INSERT INTO game_actions(id,episode_id,action_type,question_id,participant_id,point_delta,reason,metadata_json,prior_state_json,resulting_state_json,reverses_action_id) VALUES(?,?,?,?,?,?,?,'{}',?,?,?)`).run(aid,id,type,data.qid??null,data.pid??null,data.delta??0,data.reason??null,prior?JSON.stringify(prior):null,result?JSON.stringify(result):null,data.reverses??null);return aid}
function requireInProgress(e:any){if(e.status!=='in_progress')throw new LifecycleError('INVALID_TRANSITION','Live commands require an in-progress episode.')}
function requireActive(e:any){if(!e.active_question_id)throw new LifecycleError('NO_ACTIVE_QUESTION','Select a question first.');return e.active_question_id as string}
function timerRemaining(e:any,clock:Clock){return effectiveTimer(e,clock).remainingMs}

export function expireTimers(clock:Clock=()=>new Date()){const rows=db.prepare("SELECT id FROM episodes WHERE timer_status='running'").all()as any[];const expired:string[]=[];for(const r of rows){const e=episode(r.id);if(timerRemaining(e,clock)<=0){db.prepare("UPDATE episodes SET timer_status='expired',timer_remaining_ms=0,timer_expired_at=?,timer_resumed_at=NULL,revision=revision+1 WHERE id=? AND timer_status='running'").run(nowIso(clock),r.id);expired.push(r.id)}}return expired}

export function executeLiveCommand(input:LiveCommand,clock:Clock=()=>new Date()):{duplicate:boolean;revision:number}{
  const c=commandSchema.parse(input),priorCommand:any=db.prepare('SELECT resulting_revision FROM live_commands WHERE command_id=?').get(c.commandId);if(priorCommand)return{duplicate:true,revision:priorCommand.resulting_revision};
  const e=episode(c.episodeId);requireInProgress(e);if(e.revision!==c.expectedRevision)throw new LifecycleError('STALE_REVISION','The episode changed. Refresh and try again.',{expected:c.expectedRevision,actual:e.revision});
  const prior=snapshot(c.episodeId),p=c.payload as any,id=c.episodeId;let type='',data:any={};db.exec('BEGIN');try{
    if(c.type==='question.select'){const q:any=db.prepare("SELECT state FROM episode_questions WHERE episode_id=? AND question_id=?").get(id,p.questionId);if(!q)throw new LifecycleError('QUESTION_NOT_FOUND','Episode question not found.');if(q.state!=='unopened')throw new LifecycleError('QUESTION_UNAVAILABLE','Only unopened questions can be selected.');db.prepare("UPDATE episode_questions SET state='opened',opened_at=? WHERE episode_id=? AND question_id=?").run(nowIso(clock),id,p.questionId);db.prepare("UPDATE episodes SET active_question_id=?,answer_revealed=0 WHERE id=?").run(p.questionId,id);type='question_selected';data.qid=p.questionId}
    else if(c.type==='question.show'){requireActive(e);db.prepare("UPDATE episodes SET public_display_mode='question',answer_revealed=0 WHERE id=?").run(id);type='question_shown'}
    else if(c.type==='answer.reveal'){requireActive(e);db.prepare("UPDATE episodes SET answer_revealed=1,public_display_mode='answer' WHERE id=?").run(id);type='answer_revealed'}
    else if(c.type==='display.setMode'){if(!modes.includes(p.mode))throw new LifecycleError('INVALID_MODE','Unknown display mode.');if(p.mode==='final')throw new LifecycleError('INVALID_MODE','Final mode requires a completed episode.');if(['question','answer'].includes(p.mode)&&!e.active_question_id)throw new LifecycleError('INVALID_MODE','Select a question first.');if(p.mode==='answer'&&!e.answer_revealed)throw new LifecycleError('ANSWER_HIDDEN','Reveal the answer first.');db.prepare('UPDATE episodes SET public_display_mode=? WHERE id=?').run(p.mode,id);type='display_mode_changed'}
    else if(c.type==='score.adjust'){if(!Number.isInteger(p.delta)||p.delta===0)throw new LifecycleError('INVALID_SCORE','Score change must be a non-zero integer.');if(p.manual&&!String(p.reason??'').trim())throw new LifecycleError('REASON_REQUIRED','Manual adjustments require a reason.');const r=db.prepare('UPDATE episode_participants SET score=score+? WHERE episode_id=? AND id=?').run(p.delta,id,p.participantId);if(!r.changes)throw new LifecycleError('PARTICIPANT_NOT_FOUND','Participant not found.');type='score_adjusted';data={pid:p.participantId,delta:p.delta,reason:p.reason??null}}
    else if(c.type==='score.question'){if(!['award','deduct'].includes(p.direction))throw new LifecycleError('INVALID_SCORE','Question score direction must be award or deduct.');const scored=scoreActiveQuestion(id,p.participantId,p.direction);type='question_scored';data={qid:scored.questionId,pid:p.participantId,delta:scored.delta,metadata:{base:scored.base,effectKey:scored.effectKey}}}
    else if(c.type==='question.complete'||c.type==='question.skip'){const qid=requireActive(e);const q:any=db.prepare('SELECT state FROM episode_questions WHERE episode_id=? AND question_id=?').get(id,qid);if(['completed','skipped'].includes(q.state))throw new LifecycleError('QUESTION_FINALIZED','Question is already finalized.');const state=c.type==='question.skip'?'skipped':'completed';const delta=Number(p.points??0);if(delta){const r=db.prepare('UPDATE episode_participants SET score=score+? WHERE episode_id=? AND id=?').run(delta,id,p.participantId);if(!r.changes)throw new LifecycleError('PARTICIPANT_NOT_FOUND','Participant not found.')}db.prepare("UPDATE episode_questions SET state=?,completed_at=?,outcome=?,awarded_participant_id=?,awarded_points=?,modifier_status=CASE WHEN modifier_status='active' THEN 'consumed' ELSE modifier_status END WHERE episode_id=? AND question_id=?").run(state,nowIso(clock),state,p.participantId??null,delta,id,qid);db.prepare("UPDATE episodes SET active_question_id=NULL,answer_revealed=0,public_display_mode='board',timer_status='idle',timer_resumed_at=NULL,timer_expired_at=NULL WHERE id=?").run(id);type=state==='skipped'?'question_skipped':'question_completed';data={qid,pid:p.participantId,delta}}
    else if(c.type.startsWith('timer.')){const qid=requireActive(e),remaining=timerRemaining(e,clock);if(c.type==='timer.start'){const duration=Math.max(1000,Number(p.durationMs??e.timer_duration_ms));db.prepare("UPDATE episodes SET timer_duration_ms=?,timer_remaining_ms=?,timer_status='running',timer_resumed_at=?,timer_expired_at=NULL WHERE id=?").run(duration,duration,nowIso(clock),id);type='timer_started'}else if(c.type==='timer.pause'){if(e.timer_status!=='running')throw new LifecycleError('INVALID_TIMER','Timer is not running.');db.prepare("UPDATE episodes SET timer_remaining_ms=?,timer_status='paused',timer_resumed_at=NULL WHERE id=?").run(remaining,id);type='timer_paused'}else if(c.type==='timer.resume'){if(!['paused','expired'].includes(e.timer_status))throw new LifecycleError('INVALID_TIMER','Timer is not paused.');if(remaining<=0)throw new LifecycleError('INVALID_TIMER','Reset or add time before resuming.');db.prepare("UPDATE episodes SET timer_remaining_ms=?,timer_status='running',timer_resumed_at=?,timer_expired_at=NULL WHERE id=?").run(remaining,nowIso(clock),id);type='timer_resumed'}else if(c.type==='timer.reset'){const duration=Math.max(1000,Number(p.durationMs??e.timer_duration_ms));db.prepare("UPDATE episodes SET timer_duration_ms=?,timer_remaining_ms=?,timer_status='idle',timer_resumed_at=NULL,timer_expired_at=NULL WHERE id=?").run(duration,duration,id);type='timer_reset'}else{const next=Math.max(0,remaining+Number(p.deltaMs??0)),status=next===0?'expired':e.timer_status,resumed=status==='running'?nowIso(clock):null;db.prepare('UPDATE episodes SET timer_remaining_ms=?,timer_status=?,timer_resumed_at=?,timer_expired_at=? WHERE id=?').run(next,status,resumed,status==='expired'?nowIso(clock):null,id);type='timer_adjusted'}data.qid=qid}
    else if(c.type==='action.undo'){const target:any=db.prepare('SELECT * FROM game_actions WHERE episode_id=? AND prior_state_json IS NOT NULL AND undone_at IS NULL ORDER BY rowid DESC LIMIT 1').get(id);if(!target||!reversible.has(target.action_type))throw new LifecycleError('UNDO_UNAVAILABLE','There is no safe action to undo.');restore(id,JSON.parse(target.prior_state_json));const undoId=record(id,'action_undone',null,null,{reverses:target.id});db.prepare('UPDATE game_actions SET undone_at=?,compensating_action_id=? WHERE id=? AND undone_at IS NULL').run(nowIso(clock),undoId,target.id);type='';}
    if(type){const result=snapshot(id);record(id,type,prior,result,data)}
    db.prepare('UPDATE episodes SET revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(id);const revision=(db.prepare('SELECT revision FROM episodes WHERE id=?').get(id)as any).revision;db.prepare('INSERT INTO live_commands(command_id,episode_id,command_type,resulting_revision) VALUES(?,?,?,?)').run(c.commandId,id,c.type,revision);db.exec('COMMIT');return{duplicate:false,revision}
  }catch(error){db.exec('ROLLBACK');throw error}
}
