import type { Server } from 'node:http';
import { WebSocketServer,WebSocket } from 'ws';
import type { LiveCommand } from '../shared/types.js';
import { executeLiveCommand,expireTimers,getPrivateLiveState,getPublicLiveState } from './liveRepository.js';
import { executeD20Command } from './d20Repository.js';
import { executePresentationCommand } from './presentationRepository.js';
import { authenticate,buzz,contestantReady,disconnectContestant,getContestantState,heartbeatContestant } from './contestantRepository.js';
import { contestantCommandSchema } from '../shared/validation.js';

type Client=WebSocket&{episodeId?:string;role?:'host'|'audience'|'contestant';clientId?:string;alive?:boolean;contestantToken?:string;contestantSessionId?:string};
const send=(ws:Client,event:string,data:unknown)=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({event,data}))};
export function attachLiveSockets(server:Server){
  const wss=new WebSocketServer({server,path:'/ws',maxPayload:64*1024}),controllers=new Map<string,string>(),contestantConnections=new Map<string,Client>();
  const clients=(episodeId:string)=>[...wss.clients].filter(c=>(c as Client).episodeId===episodeId)as Client[];
  const counts=(id:string)=>clients(id).filter(c=>c.role==='audience').length;
  const broadcast=(id:string)=>{for(const c of clients(id)){try{if(c.role==='audience')send(c,'state.public',getPublicLiveState(id));else if(c.role==='contestant')send(c,'state.contestant',getContestantState(c.contestantToken!));else send(c,'state.private',getPrivateLiveState(id,{role:controllers.get(id)===c.clientId?'controller':'observer',controllerConnected:controllers.has(id),audienceCount:counts(id)}))}catch{if(c.role==='contestant')c.close(1008,'Session unavailable')}}};
  const reject=(c:Client,error:any)=>send(c,'command.rejected',{code:error?.code??'INVALID_COMMAND',message:error?.message??'Command rejected.',details:error?.details});
  wss.on('connection',(ws:Client,request)=>{try{const url=new URL(request.url??'',`http://${request.headers.host??'localhost'}`),role=url.searchParams.get('role');let episodeId=url.searchParams.get('episodeId');if(role==='contestant'){const raw=url.searchParams.get('sessionToken');if(!raw)throw new Error('Invalid subscription');const s=authenticate(raw);episodeId=s.episode_id;ws.contestantToken=raw;ws.contestantSessionId=s.id;const prior=contestantConnections.get(s.id);if(prior&&prior!==ws)prior.close(4009,'Session opened on another device');contestantConnections.set(s.id,ws)}else if(!episodeId||!['host','audience'].includes(role??'')){ws.close(1008,'Invalid subscription');return}ws.episodeId=episodeId!;ws.role=role as any;ws.clientId=url.searchParams.get('clientId')||crypto.randomUUID();ws.alive=true;if(role==='host'&&!controllers.has(episodeId!))controllers.set(episodeId!,ws.clientId);broadcast(episodeId!);
      ws.on('pong',()=>{ws.alive=true;if(role==='contestant')try{heartbeatContestant(ws.contestantToken!)}catch{ws.close(1008,'Session unavailable')}});ws.on('message',raw=>{try{if(raw.toString().length>64*1024)throw new Error('Message too large.');const message=JSON.parse(raw.toString());if(role==='contestant'){const c=contestantCommandSchema.parse(message);if(c.type==='contestant.ready'||c.type==='contestant.notReady')contestantReady(ws.contestantToken!,c.type==='contestant.ready');else if(c.type==='contestant.leave')disconnectContestant(ws.contestantToken!,true);else if(c.type==='contestant.buzz')send(ws,'command.accepted',buzz(ws.contestantToken!,c));broadcast(episodeId!);return}if(message.type==='state.resync'){broadcast(episodeId!);return}if(role!=='host')throw new Error('Audience connections are read-only.');if(message.type==='host.claimControl'){controllers.set(episodeId!,ws.clientId!);broadcast(episodeId!);return}if(message.type==='host.releaseControl'){if(controllers.get(episodeId!)===ws.clientId)controllers.delete(episodeId!);broadcast(episodeId!);return}if(message.type!=='command')throw new Error('Unknown message type.');if(controllers.get(episodeId!)!==ws.clientId)throw Object.assign(new Error('This Host Console is an observer. Take control before issuing commands.'),{code:'CONTROL_REQUIRED'});const command=message.command as LiveCommand;if(command.episodeId!==episodeId)throw new Error('Episode mismatch.');const result=command.type.startsWith('d20.')?executeD20Command(command):command.type.startsWith('presentation.')?executePresentationCommand(command):executeLiveCommand(command);send(ws,'command.accepted',{commandId:command.commandId,...result});broadcast(episodeId!)}catch(error){reject(ws,error)}});
      ws.on('close',()=>{if(role==='contestant'&&contestantConnections.get(ws.contestantSessionId!)===ws){contestantConnections.delete(ws.contestantSessionId!);try{disconnectContestant(ws.contestantToken!)}catch{}}if(role==='host'&&controllers.get(episodeId!)===ws.clientId){controllers.delete(episodeId!);const next=clients(episodeId!).find(c=>c!==ws&&c.role==='host');if(next)controllers.set(episodeId!,next.clientId!)}broadcast(episodeId!)})
    }catch{ws.close(1011,'Subscription failed')}});
  const heartbeat=setInterval(()=>{for(const ws of wss.clients as Set<Client>){if(ws.alive===false){ws.terminate();continue}ws.alive=false;ws.ping()}for(const id of expireTimers())broadcast(id)},1000);heartbeat.unref();wss.on('close',()=>clearInterval(heartbeat));
  return{wss,broadcast};
}
