import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type {
  AudioState,
  LiveCommand,
  PresentationLayout,
  PresentationScene,
  PresentationTransition,
  PrivatePresentationState,
  PublicPresentationState,
  SafeAreaConfig,
  ThemeTokens,
} from "../shared/types.js";
import { db } from "./db/database.js";
import { LifecycleError } from "./episodesRepository.js";
import { normalizeThemeConfig,themeTokensFromConfig } from './themeDesignerRepository.js';

export const scenes: PresentationScene[] = ["standby","intro","board","question","answer","scores","d20","intermission","round-transition","winner","final","credits","custom-message"];
export const layouts: PresentationLayout[] = ["full","overlay","scorebug","question","lowerthird"];
const transitions = new Set(["cut","fade","crossfade","slide-left","slide-right","slide-up","zoom","card-flip","wipe","glitch","iris","score-pulse","category-reveal","question-reveal","answer-reveal","winner-reveal"]);
const transition: PresentationTransition = {kind:"fade",durationMs:650,easing:"cubic-bezier(.2,.8,.2,1)",delayMs:0,reducedMotionFallback:"cut",audioCue:null,backgroundHold:true,interrupt:"settle"};
const safeArea: SafeAreaConfig = {titleSafePercent:10,actionSafePercent:5,cameraZones:[],showGuides:false};
const groups=["master","music","stingers","ui","timer","d20","winner","ambient"];
const audio: AudioState={masterMuted:false,reducedAudio:false,audienceOnly:true,groups:Object.fromEntries(groups.map(x=>[x,{muted:false,volume:1}])),cue:null};
const theme=(id:string,name:string,colors:ThemeTokens["colors"],fonts:ThemeTokens["fonts"],motionIntensity:number):ThemeTokens=>({id,name,description:`Original ${name} broadcast package.`,colors,fonts,shape:{radius:"18px",border:"1px solid color-mix(in srgb, var(--accent) 50%, transparent)",shadow:"0 24px 80px #0009",glow:"0 0 36px color-mix(in srgb, var(--accent) 45%, transparent)"},motionIntensity,logoPlacement:"top-left",watermarkPlacement:"bottom-right",transitionDefaults:transition});
const fonts={display:"Impact, Haettenschweiler, sans-serif",heading:"system-ui, sans-serif",body:"system-ui, sans-serif",score:"ui-monospace, monospace",timer:"ui-monospace, monospace",question:"system-ui, sans-serif"};
export const builtinThemes:ThemeTokens[]=[
 theme("nerd-wars-classic","Nerd Wars Classic",{primary:"#7c3aed",secondary:"#06b6d4",background:"#070712",surface:"#17152a",accent:"#facc15",success:"#22c55e",warning:"#f59e0b",error:"#ef4444",text:"#f8fafc",muted:"#a5b4c8"},fonts,0.75),
 theme("neon-arcade","Neon Arcade",{primary:"#ff2bd6",secondary:"#00f5ff",background:"#050019",surface:"#17072f",accent:"#b8ff2c",success:"#2cff88",warning:"#ffe44d",error:"#ff365e",text:"#ffffff",muted:"#b8a8d8"},{...fonts,display:"Arial Black, system-ui, sans-serif"},1),
 theme("fantasy-codex","Fantasy Codex",{primary:"#9a6a32",secondary:"#476b52",background:"#17120c",surface:"#2a2115",accent:"#dfbd75",success:"#77a66b",warning:"#d99545",error:"#b64e42",text:"#fff4d6",muted:"#c9b78f"},{...fonts,display:"Georgia, serif",heading:"Georgia, serif",question:"Georgia, serif"},0.45)
];
const profiles=[
 {id:"nerd-wars",name:"Nerd Wars",isDefault:true,config:{showTitle:"NERD WARS",subtitle:"Geek Trivia Live",themeId:"nerd-wars-classic",logoAssetId:null,watermarkAssetId:null,sponsorAssetId:null,defaultLayout:"full",d20Theme:"neon_arcane",safeArea,audioProfileId:"generated-default"}},
 {id:"geek-trivia-classic",name:"Geek Trivia Classic",isDefault:false,config:{showTitle:"GEEK TRIVIA",subtitle:"Live Game Show",themeId:"neon-arcade",logoAssetId:null,watermarkAssetId:null,sponsorAssetId:null,defaultLayout:"full",d20Theme:"classic_polyhedral",safeArea,audioProfileId:"generated-default"}}
];
const assetDir=path.resolve("data/presentation-assets");
const parse=(v:any,fallback:any)=>{try{return typeof v==="string"?JSON.parse(v):v??fallback}catch{return fallback}};
function ensureDefaults(){
 for(const t of builtinThemes)db.prepare("INSERT OR IGNORE INTO presentation_themes(id,name,description,config_json,is_builtin) VALUES(?,?,?,?,1)").run(t.id,t.name,t.description,JSON.stringify(t));
 for(const p of profiles)db.prepare("INSERT OR IGNORE INTO branding_profiles(id,name,config_json,is_default) VALUES(?,?,?,?)").run(p.id,p.name,JSON.stringify(p.config),p.isDefault?1:0);
 for(const scene of scenes)db.prepare("INSERT OR IGNORE INTO scene_templates(id,scene_type,name,config_json,is_builtin) VALUES(?,?,?,?,1)").run(`builtin-${scene}`,scene,scene.replaceAll("-"," "),JSON.stringify({scene,transition}));
 db.prepare("INSERT OR IGNORE INTO audio_profiles(id,name,config_json) VALUES('generated-default','Generated Tones',?)").run(JSON.stringify({license:"Original tones generated at runtime; no bundled recordings.",groups:audio.groups}));
}
function episode(id:string):any{const row=db.prepare("SELECT * FROM episodes WHERE id=?").get(id);if(!row)throw new LifecycleError("EPISODE_NOT_FOUND","Episode not found.");return row}
function state(id:string):any{ensureDefaults();const e=episode(id),initial=scenes.includes(e.public_display_mode)?e.public_display_mode:"standby";db.prepare("INSERT OR IGNORE INTO presentation_state(episode_id,program_scene,preview_scene) VALUES(?,?,?)").run(id,initial,initial);return db.prepare("SELECT * FROM presentation_state WHERE episode_id=?").get(id)}
function publicAsset(id:string|null){if(!id)return null;const a:any=db.prepare("SELECT id FROM presentation_assets WHERE id=? AND active=1").get(id);return a?`/api/presentation/assets/${encodeURIComponent(a.id)}`:null}
function normalizedTransition(raw:any):PresentationTransition{const v={...transition,...parse(raw,{})};return{...v,kind:transitions.has(v.kind)?v.kind:"fade",durationMs:Math.min(5000,Math.max(0,Number(v.durationMs)||0)),delayMs:Math.min(2000,Math.max(0,Number(v.delayMs)||0)),reducedMotionFallback:transitions.has(v.reducedMotionFallback)?v.reducedMotionFallback:"cut"}}
export function getPublicPresentation(id:string):PublicPresentationState{
 const s=state(id),p:any=db.prepare("SELECT * FROM branding_profiles WHERE id=?").get(s.profile_id)??db.prepare("SELECT * FROM branding_profiles WHERE is_default=1").get(),pc=parse(p.config_json,{}),t:any=db.prepare("SELECT id,name,published_json,config_json FROM presentation_themes WHERE id=?").get(s.theme_id)??db.prepare("SELECT id,name,published_json,config_json FROM presentation_themes WHERE id='nerd-wars-classic'").get(),theme=themeTokensFromConfig(t.id,normalizeThemeConfig(t.published_json??t.config_json,t.name)),now=Date.now(),ends=s.transition_ends_at?Date.parse(s.transition_ends_at):0,tr=normalizedTransition(s.transition_json);
 const branding=theme.designer?.branding;
 return{programScene:s.program_scene,transition:{...tr,startedAt:ends>now?s.transition_started_at:null,endsAt:ends>now?s.transition_ends_at:null},theme,profile:{name:p.name,showTitle:pc.showTitle??p.name,subtitle:pc.subtitle??"",logoUrl:publicAsset(branding?.logoAssetId??pc.logoAssetId),watermarkUrl:publicAsset(branding?.watermarkAssetId??pc.watermarkAssetId),sponsorUrl:publicAsset(branding?.sponsorAssetId??pc.sponsorAssetId)},layout:layouts.includes(s.layout)?s.layout:"full",audio:parse(s.audio_json,audio),graphics:(db.prepare("SELECT id,graphic_type,public_payload_json,expires_at FROM graphic_overlays WHERE episode_id=? AND visible=1 AND (expires_at IS NULL OR expires_at>CURRENT_TIMESTAMP)").all(id)as any[]).map(x=>({id:x.id,type:x.graphic_type,text:String(parse(x.public_payload_json,{}).text??""),expiresAt:x.expires_at})),safeArea:parse(s.safe_area_json,safeArea),customMessage:s.custom_message,reducedMotion:Boolean(s.reduced_motion),animationsDisabled:Boolean(s.animations_disabled)};
}
export function getPrivatePresentation(id:string):PrivatePresentationState{const pub=getPublicPresentation(id),s=state(id),now=Date.now();return{...pub,previewScene:s.preview_scene,queuedScene:s.queued_scene,availableScenes:scenes,availableThemes:(db.prepare("SELECT id,name FROM presentation_themes ORDER BY is_builtin DESC,name").all()as any[]),availableProfiles:(db.prepare("SELECT id,name,is_default FROM branding_profiles ORDER BY is_default DESC,name").all()as any[]).map(x=>({id:x.id,name:x.name,isDefault:Boolean(x.is_default)})),transitionStatus:s.queued_scene?"queued":s.transition_ends_at&&Date.parse(s.transition_ends_at)>now?"transitioning":"idle",assetCount:(db.prepare("SELECT count(*) n FROM presentation_assets WHERE active=1").get()as any).n};}
const iso=(ms:number)=>new Date(ms).toISOString();
export function executePresentationCommand(input:LiveCommand){const prior:any=db.prepare("SELECT resulting_revision FROM live_commands WHERE command_id=?").get(input.commandId);if(prior)return{duplicate:true,revision:prior.resulting_revision};const e=episode(input.episodeId);if(e.status!=="in_progress")throw new LifecycleError("INVALID_TRANSITION","Presentation commands require an in-progress episode.");if(e.revision!==input.expectedRevision)throw new LifecycleError("STALE_REVISION","The episode changed. Refresh and try again.",{expected:input.expectedRevision,actual:e.revision});const s=state(input.episodeId),p=input.payload as any;db.exec("BEGIN");try{
  if(input.type==="presentation.previewScene"){if(!scenes.includes(p.scene))throw new LifecycleError("INVALID_SCENE","Unknown presentation scene.");db.prepare("UPDATE presentation_state SET preview_scene=? WHERE episode_id=?").run(p.scene,input.episodeId)}
  else if(input.type==="presentation.queueScene"){if(!scenes.includes(p.scene))throw new LifecycleError("INVALID_SCENE","Unknown presentation scene.");db.prepare("UPDATE presentation_state SET preview_scene=?,queued_scene=? WHERE episode_id=?").run(p.scene,p.scene,input.episodeId)}
  else if(input.type==="presentation.cancelQueue")db.prepare("UPDATE presentation_state SET queued_scene=NULL WHERE episode_id=?").run(input.episodeId);
  else if(input.type==="presentation.take"||input.type==="presentation.cut"){const scene=p.scene??s.queued_scene??s.preview_scene;if(!scenes.includes(scene))throw new LifecycleError("INVALID_SCENE","Choose a valid Preview scene first.");const tr=normalizedTransition(input.type==="presentation.cut"?{kind:"cut",durationMs:0}:p.transition??s.transition_json),start=Date.now()+tr.delayMs,end=start+tr.durationMs;db.prepare("UPDATE presentation_state SET program_scene=?,preview_scene=?,queued_scene=NULL,transition_json=?,transition_started_at=?,transition_ends_at=?,updated_at=CURRENT_TIMESTAMP WHERE episode_id=?").run(scene,scene,JSON.stringify(tr),tr.durationMs?iso(start):null,tr.durationMs?iso(end):null,input.episodeId)}
  else if(input.type==="presentation.setTheme"){if(!db.prepare("SELECT 1 FROM presentation_themes WHERE id=?").get(p.themeId))throw new LifecycleError("INVALID_THEME","Theme not found.");db.prepare("UPDATE presentation_state SET theme_id=? WHERE episode_id=?").run(p.themeId,input.episodeId)}
  else if(input.type==="presentation.setProfile"){if(!db.prepare("SELECT 1 FROM branding_profiles WHERE id=?").get(p.profileId))throw new LifecycleError("INVALID_PROFILE","Branding profile not found.");db.prepare("UPDATE presentation_state SET profile_id=? WHERE episode_id=?").run(p.profileId,input.episodeId)}
  else if(input.type==="presentation.setLayout"){if(!layouts.includes(p.layout))throw new LifecycleError("INVALID_LAYOUT","Unknown presentation layout.");db.prepare("UPDATE presentation_state SET layout=? WHERE episode_id=?").run(p.layout,input.episodeId)}
  else if(input.type==="presentation.triggerGraphic"){const text=String(p.text??"").slice(0,240);db.prepare("INSERT INTO graphic_overlays(id,episode_id,graphic_type,public_payload_json,expires_at) VALUES(?,?,?,?,?)").run(crypto.randomUUID(),input.episodeId,String(p.graphicType??"custom-message"),JSON.stringify({text}),p.durationMs?iso(Date.now()+Math.min(60000,Math.max(1000,p.durationMs))):null)}
  else if(input.type==="presentation.hideGraphic")db.prepare("UPDATE graphic_overlays SET visible=0 WHERE id=? AND episode_id=?").run(p.graphicId,input.episodeId);
  else if(input.type==="presentation.playCue"||input.type==="presentation.stopCue"||input.type==="presentation.setAudioState"){const a=parse(s.audio_json,audio),next=input.type==="presentation.stopCue"?{...a,cue:null}:input.type==="presentation.playCue"?{...a,cue:{id:crypto.randomUUID(),type:String(p.cueType??"ui"),startedAt:new Date().toISOString(),loop:Boolean(p.loop)}}:{...a,...p,groups:{...a.groups,...(p.groups??{})}};for(const g of Object.values(next.groups)as any[])g.volume=Math.min(1,Math.max(0,Number(g.volume)));db.prepare("UPDATE presentation_state SET audio_json=? WHERE episode_id=?").run(JSON.stringify(next),input.episodeId)}
  else if(input.type==="presentation.setOptions"){const patch={reduced_motion:p.reducedMotion?1:0,animations_disabled:p.animationsDisabled?1:0,safe_area_json:JSON.stringify({...safeArea,...p.safeArea}),custom_message:p.customMessage?String(p.customMessage).slice(0,500):null};db.prepare("UPDATE presentation_state SET reduced_motion=?,animations_disabled=?,safe_area_json=?,custom_message=? WHERE episode_id=?").run(patch.reduced_motion,patch.animations_disabled,patch.safe_area_json,patch.custom_message,input.episodeId)}
  else if(input.type!=="presentation.resync")throw new LifecycleError("INVALID_PRESENTATION_COMMAND","Unknown presentation command.");
  db.prepare("UPDATE episodes SET revision=revision+1,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(input.episodeId);const revision=(db.prepare("SELECT revision FROM episodes WHERE id=?").get(input.episodeId)as any).revision;db.prepare("INSERT INTO live_commands(command_id,episode_id,command_type,resulting_revision) VALUES(?,?,?,?)").run(input.commandId,input.episodeId,input.type,revision);db.exec("COMMIT");return{duplicate:false,revision};
 }catch(error){db.exec("ROLLBACK");throw error}}

export function listThemes(){ensureDefaults();return db.prepare("SELECT id,name,description,config_json,is_builtin FROM presentation_themes ORDER BY is_builtin DESC,name").all()}
export function listProfiles(){ensureDefaults();return(db.prepare("SELECT * FROM branding_profiles ORDER BY is_default DESC,name").all()as any[]).map(x=>({...x,config:parse(x.config_json,{})}))}
function validateProfile(config:any){if(!String(config.showTitle??"").trim())throw new LifecycleError("INVALID_PROFILE","Show title is required.");if(!db.prepare("SELECT 1 FROM presentation_themes WHERE id=?").get(config.themeId))throw new LifecycleError("INVALID_PROFILE","Profile references an invalid theme.");for(const key of["logoAssetId","watermarkAssetId","sponsorAssetId"])if(config[key]&&!db.prepare("SELECT 1 FROM presentation_assets WHERE id=? AND active=1").get(config[key]))throw new LifecycleError("MISSING_ASSET",`Profile ${key} is missing.`)}
export function saveProfile(input:any){ensureDefaults();const config=input.config??input;validateProfile(config);const id=input.id?String(input.id):crypto.randomUUID();db.prepare("INSERT INTO branding_profiles(id,name,config_json,is_default) VALUES(?,?,?,0) ON CONFLICT(id) DO UPDATE SET name=excluded.name,config_json=excluded.config_json,updated_at=CURRENT_TIMESTAMP").run(id,String(input.name??config.showTitle).slice(0,100),JSON.stringify(config));return listProfiles().find(x=>x.id===id)}
export function duplicateProfile(id:string){const p:any=db.prepare("SELECT * FROM branding_profiles WHERE id=?").get(id);if(!p)throw new LifecycleError("PROFILE_NOT_FOUND","Profile not found.");return saveProfile({name:`${p.name} Copy`,config:parse(p.config_json,{})})}
export function deleteProfile(id:string){const p:any=db.prepare("SELECT is_default FROM branding_profiles WHERE id=?").get(id);if(!p)throw new LifecycleError("PROFILE_NOT_FOUND","Profile not found.");if(p.is_default)throw new LifecycleError("DEFAULT_PROFILE","The default profile cannot be deleted.");if(db.prepare("SELECT 1 FROM presentation_state WHERE profile_id=? LIMIT 1").get(id))throw new LifecycleError("PROFILE_IN_USE","Replace this profile before deleting it.");db.prepare("DELETE FROM branding_profiles WHERE id=?").run(id)}
const allowedMime:Record<string,string>={"image/png":"png","image/jpeg":"jpg","image/webp":"webp","audio/mpeg":"mp3","audio/wav":"wav","audio/ogg":"ogg","video/mp4":"mp4","font/woff2":"woff2"};
function validSignature(mime:string,b:Buffer){const ascii=(a:number,z:number)=>b.subarray(a,z).toString('ascii');if(mime==='image/png')return b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(mime==='image/jpeg')return b[0]===255&&b[1]===216&&b[2]===255;if(mime==='image/webp')return ascii(0,4)==='RIFF'&&ascii(8,12)==='WEBP';if(mime==='audio/wav')return ascii(0,4)==='RIFF'&&ascii(8,12)==='WAVE';if(mime==='audio/ogg')return ascii(0,4)==='OggS';if(mime==='audio/mpeg')return ascii(0,3)==='ID3'||(b[0]===255&&(b[1]&224)===224);if(mime==='video/mp4')return ascii(4,8)==='ftyp';if(mime==='font/woff2')return ascii(0,4)==='wOF2';return false}
export function saveAsset(input:any){const mime=String(input.mimeType??"").toLowerCase(),ext=allowedMime[mime];if(!ext)throw new LifecycleError("UNSAFE_ASSET_TYPE","Unsupported or unsafe asset type.");const bytes=Buffer.from(String(input.base64??""),"base64");if(!bytes.length||bytes.length>25*1024*1024)throw new LifecycleError("INVALID_ASSET_SIZE","Assets must be between 1 byte and 25 MB.");if(!validSignature(mime,bytes))throw new LifecycleError("ASSET_SIGNATURE_MISMATCH","File content does not match its declared MIME type.");const original=path.basename(String(input.fileName??`asset.${ext}`)).replace(/[^a-zA-Z0-9._-]/g,"_");if(original.includes("..")||/[\\/]/.test(String(input.fileName??"")))throw new LifecycleError("UNSAFE_FILENAME","Unsafe asset filename.");fs.mkdirSync(assetDir,{recursive:true});const id=crypto.randomUUID(),stored=`${id}.${ext}`,checksum=crypto.createHash("sha256").update(bytes).digest("hex");fs.writeFileSync(path.join(assetDir,stored),bytes,{flag:"wx"});db.prepare("INSERT INTO presentation_assets(id,display_name,asset_type,stored_name,original_name,mime_type,file_size,checksum,licensing_note,attribution_note) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,String(input.displayName??original).slice(0,120),String(input.assetType??"image"),stored,original,mime,bytes.length,checksum,String(input.licensingNote??"").slice(0,500),String(input.attributionNote??"").slice(0,500));return{id,displayName:input.displayName??original,mimeType:mime,fileSize:bytes.length,url:`/api/presentation/assets/${id}`}}
export function listAssets(){return(db.prepare("SELECT id,display_name,asset_type,original_name,mime_type,file_size,width,height,duration_ms,checksum,licensing_note,attribution_note,active,created_at,updated_at FROM presentation_assets ORDER BY created_at DESC").all()as any[]).map(x=>({...x,url:`/api/presentation/assets/${x.id}`}))}
export function assetFile(id:string){const a:any=db.prepare("SELECT stored_name,mime_type FROM presentation_assets WHERE id=? AND active=1").get(id);if(!a)return null;const file=path.join(assetDir,a.stored_name);if(!file.startsWith(assetDir+path.sep)||!fs.existsSync(file))return null;return{file,mime:a.mime_type}}
export function deleteAsset(id:string,force=false){const refs=(db.prepare("SELECT id,config_json FROM branding_profiles").all()as any[]).filter(x=>JSON.stringify(parse(x.config_json,{})).includes(id));if(refs.length&&!force)throw new LifecycleError("ASSET_IN_USE","Asset is referenced by a branding profile.",{references:refs.map(x=>x.id)});db.prepare("UPDATE presentation_assets SET active=0 WHERE id=?").run(id)}
export function exportPresentationBackup(){ensureDefaults();return{themes:db.prepare("SELECT * FROM presentation_themes").all(),profiles:db.prepare("SELECT * FROM branding_profiles").all(),templates:db.prepare("SELECT * FROM scene_templates").all(),states:db.prepare("SELECT * FROM presentation_state").all(),assets:db.prepare("SELECT * FROM presentation_assets").all(),audioProfiles:db.prepare("SELECT * FROM audio_profiles").all(),cues:db.prepare("SELECT * FROM presentation_cues").all()}}
export function restorePresentationBackup(data:any){if(!data){ensureDefaults();return}const sets:[[string,any[]],...Array<[string,any[]]>]=[["presentation_themes",data.themes??[]],["branding_profiles",data.profiles??[]],["scene_templates",data.templates??[]],["presentation_state",data.states??[]],["presentation_assets",data.assets??[]],["audio_profiles",data.audioProfiles??[]],["presentation_cues",data.cues??[]]];db.exec("BEGIN");try{for(const[table,rows]of sets)for(const row of rows){const keys=Object.keys(row);if(!keys.length)continue;db.prepare(`INSERT OR REPLACE INTO ${table}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(...keys.map(k=>row[k]))}db.exec("COMMIT");ensureDefaults()}catch(error){db.exec("ROLLBACK");throw error}}
