import type { Question } from '../shared/types.js'; import { db,rowToQuestion } from './db/database.js';
export interface QuestionFilters {search?:string;category?:string;subcategory?:string;difficulty?:number;active?:boolean;usage?:'used'|'unused'}
const columns=`id,category,subcategory,difficulty,point_value,question_text,correct_answer,alternate_answers,question_type,media_path,host_notes,source,active,used_count,date_last_used,episode_last_used`;
const values=(q:Question)=>[q.id,q.category,q.subcategory,q.difficulty,q.difficulty*100,q.questionText,q.correctAnswer,JSON.stringify(q.alternateAnswers),q.questionType,q.mediaPath,q.hostNotes,q.source,Number(q.active),q.usedCount,q.dateLastUsed,q.episodeLastUsed];
export function listQuestions(filters:QuestionFilters={}):Question[]{const clauses:string[]=[];const params:any[]=[];if(filters.search){clauses.push('(question_text LIKE ? OR correct_answer LIKE ? OR id LIKE ?)');params.push(...Array(3).fill(`%${filters.search}%`))}if(filters.category){clauses.push('category=?');params.push(filters.category)}if(filters.subcategory){clauses.push('subcategory=?');params.push(filters.subcategory)}if(filters.difficulty){clauses.push('difficulty=?');params.push(filters.difficulty)}if(filters.active!==undefined){clauses.push('active=?');params.push(Number(filters.active))}if(filters.usage){clauses.push(filters.usage==='used'?'used_count>0':'used_count=0')}return db.prepare(`SELECT * FROM questions ${clauses.length?'WHERE '+clauses.join(' AND '):''} ORDER BY category,difficulty,id`).all(...params).map(rowToQuestion)}
export function getQuestion(id:string):Question|undefined{const row=db.prepare('SELECT * FROM questions WHERE id=?').get(id);return row?rowToQuestion(row):undefined}
export function createQuestion(q:Question){db.prepare(`INSERT INTO questions(${columns}) VALUES(${Array(16).fill('?').join(',')})`).run(...values(q));return getQuestion(q.id)!}
export function updateQuestion(id:string,q:Question){if(id!==q.id)throw new Error('Question ID cannot be changed.');const assignments=columns.split(',').slice(1).map(c=>`${c}=?`).join(',');const result=db.prepare(`UPDATE questions SET ${assignments},updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(...values(q).slice(1),id);if(!result.changes)throw new Error('Question not found.');return getQuestion(id)!}
export function deleteQuestion(id:string){return db.prepare('DELETE FROM questions WHERE id=?').run(id).changes>0}
export function duplicateQuestion(id:string,newId:string){const q=getQuestion(id);if(!q)throw new Error('Question not found.');return createQuestion({...q,id:newId,usedCount:0,dateLastUsed:null,episodeLastUsed:null})}
export function importQuestions(items:Question[]){db.exec('BEGIN');try{items.forEach(createQuestion);db.exec('COMMIT');return items.length}catch(e){db.exec('ROLLBACK');throw e}}
