import crypto from 'node:crypto';
import { ZodError } from 'zod';
import { defaultThemeConfig, themeConfigSchema, type ThemeConfig } from '../shared/themeDesigner.js';
import type { ThemeTokens } from '../shared/types.js';
import { db } from './db/database.js';
import { LifecycleError } from './episodesRepository.js';

const parse=(value:unknown,fallback:unknown=null)=>{try{return typeof value==='string'?JSON.parse(value):value??fallback}catch{return fallback}};
const row=(id:string):any=>db.prepare('SELECT * FROM presentation_themes WHERE id=?').get(id);
const hash=(value:string)=>crypto.createHash('sha256').update(value).digest('hex');
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||'custom-theme';

export function normalizeThemeConfig(raw:unknown,name='Custom Theme'):ThemeConfig{
 const parsed=parse(raw,raw);
 const result=themeConfigSchema.safeParse(parsed);
 if(result.success)return result.data;
 const legacy=parsed as any,config=defaultThemeConfig(name);
 if(legacy?.colors){const map:any={...config.colors,...legacy.colors};if(legacy.colors.muted)map.mutedText=legacy.colors.muted;config.colors=map}
 if(legacy?.fonts){config.typography.showTitle.fontFamily=legacy.fonts.display??config.typography.showTitle.fontFamily;config.typography.sceneTitle.fontFamily=legacy.fonts.heading??config.typography.sceneTitle.fontFamily;config.typography.question.fontFamily=legacy.fonts.question??config.typography.question.fontFamily;config.typography.score.fontFamily=legacy.fonts.score??config.typography.score.fontFamily;config.typography.timer.fontFamily=legacy.fonts.timer??config.typography.timer.fontFamily}
 config.metadata.name=legacy?.name??name;config.metadata.description=legacy?.description??config.metadata.description;config.global.motion=Number.isFinite(legacy?.motionIntensity)?legacy.motionIntensity:config.global.motion;
 return themeConfigSchema.parse(config)
}

export function themeTokensFromConfig(id:string,config:ThemeConfig):ThemeTokens{
 const c=config.colors,t=config.typography;
 return{id,name:config.metadata.name,description:config.metadata.description,colors:{primary:c.primary,secondary:c.secondary,background:c.background,surface:c.surface,accent:c.accent,success:c.success,warning:c.warning,error:c.error,text:c.text,muted:c.mutedText},fonts:{display:t.showTitle.fontFamily,heading:t.sceneTitle.fontFamily,body:t.caption.fontFamily,score:t.score.fontFamily,timer:t.timer.fontFamily,question:t.question.fontFamily},shape:{radius:`${config.global.radius}px`,border:`${config.global.borderWidth}px solid ${c.border}`,shadow:`0 ${Math.round(config.global.shadow/3)}px ${config.global.shadow}px #0009`,glow:`0 0 ${config.global.glow}px ${c.accent}66`},motionIntensity:config.global.motion,logoPlacement:'top-left',watermarkPlacement:'bottom-right',transitionDefaults:{kind:config.transitions.defaultKind,durationMs:config.transitions.durationMs,easing:config.transitions.easing,delayMs:0,reducedMotionFallback:config.transitions.reducedMotionFallback,audioCue:null,backgroundHold:true,interrupt:'settle'},designer:config}
}

function serialize(theme:any){const draft=normalizeThemeConfig(theme.draft_json??theme.config_json,theme.name),published=normalizeThemeConfig(theme.published_json??theme.config_json,theme.name);return{id:theme.id,name:theme.name,description:theme.description,isBuiltin:Boolean(theme.is_builtin),status:theme.status,revision:theme.revision,publishedVersion:theme.published_version,publishedAt:theme.published_at,updatedAt:theme.updated_at,draft,published,hasDraftChanges:JSON.stringify(draft)!==JSON.stringify(published)}}
export function listDesignerThemes(){return(db.prepare('SELECT * FROM presentation_themes ORDER BY is_builtin DESC,name').all()as any[]).map(serialize)}
export function getDesignerTheme(id:string){const theme=row(id);if(!theme)throw new LifecycleError('THEME_NOT_FOUND','Theme not found.');return{...serialize(theme),versions:listThemeVersions(id)}}

export function validateTheme(raw:unknown,confirmContrast=false){
 const errors:Array<{section:string;path:string;message:string}>=[],warnings:Array<{section:string;path:string;message:string}>=[];let config:ThemeConfig|null=null;
 try{config=themeConfigSchema.parse(raw)}catch(error){if(error instanceof ZodError)for(const issue of error.issues)errors.push({section:String(issue.path[0]??'general'),path:issue.path.join('.'),message:issue.message});else throw error}
 if(config){for(const ref of config.assetReferences)if(!db.prepare('SELECT 1 FROM presentation_assets WHERE id=? AND active=1').get(ref.assetId))errors.push({section:'assets',path:`assetReferences.${ref.assetId}`,message:'Referenced asset is missing or inactive.'});const contrast=contrastRatio(config.colors.text,config.colors.background);if(contrast<3){const problem={section:'colors',path:'colors.text',message:`Severe text/background contrast (${contrast.toFixed(2)}:1).`};if(confirmContrast)warnings.push(problem);else errors.push({...problem,message:`${problem.message} Confirm severe contrast to publish.`})}else if(contrast<4.5)warnings.push({section:'colors',path:'colors.text',message:`Low text/background contrast (${contrast.toFixed(2)}:1).`});if(config.safeAreas.actionSafePercent>config.safeAreas.titleSafePercent)errors.push({section:'safeAreas',path:'safeAreas.actionSafePercent',message:'Action safe margin cannot exceed title safe margin.'});if(config.board.fiveColumnScale*config.global.contentScale>1.4)warnings.push({section:'board',path:'board.fiveColumnScale',message:'Five-column board may overflow at this content scale.'});if(config.scoreboard.maxParticipants<8)warnings.push({section:'scoreboard',path:'scoreboard.maxParticipants',message:'Eight-player preview will truncate.'});}
 return{valid:errors.length===0,errors,warnings,config}
}
function luminance(color:string){const rgb=[1,3,5].map(i=>parseInt(color.slice(i,i+2),16)/255).map(value=>value<=.03928?value/12.92:((value+.055)/1.055)**2.4);return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]}
export function contrastRatio(a:string,b:string){const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05)}

export function duplicateTheme(id:string,name?:string){const source=getDesignerTheme(id),copy=structuredClone(source.published)as ThemeConfig,copyName=String(name??`${source.name} Copy`).slice(0,100),newId=`${slug(copyName)}-${crypto.randomBytes(3).toString('hex')}`;copy.metadata.name=copyName;copy.metadata.description=`Editable copy of ${source.name}.`;const json=JSON.stringify(copy);db.prepare("INSERT INTO presentation_themes(id,name,description,config_json,draft_json,published_json,status,revision,published_version,is_builtin) VALUES(?,?,?,?,?,?,'draft',1,1,0)").run(newId,copyName,copy.metadata.description,json,json,json);const versionId=crypto.randomUUID();db.prepare("INSERT INTO theme_versions(id,theme_id,version_number,config_json,change_summary,active_published,published_at) VALUES(?,?,?,?,?,1,CURRENT_TIMESTAMP)").run(versionId,newId,1,json,`Duplicated from ${source.name}`);return getDesignerTheme(newId)}
export function createTheme(input:any){const config=themeConfigSchema.parse(input.config??defaultThemeConfig(input.name)),name=String(input.name??config.metadata.name).slice(0,100),id=`${slug(name)}-${crypto.randomBytes(3).toString('hex')}`;config.metadata.name=name;db.prepare("INSERT INTO presentation_themes(id,name,description,config_json,draft_json,published_json,status,revision,published_version,is_builtin) VALUES(?,?,?,?,?,?,'draft',1,0,0)").run(id,name,config.metadata.description,JSON.stringify(config),JSON.stringify(config),JSON.stringify(config));return getDesignerTheme(id)}
export function saveThemeDraft(id:string,raw:unknown){const theme=row(id);if(!theme)throw new LifecycleError('THEME_NOT_FOUND','Theme not found.');if(theme.is_builtin)throw new LifecycleError('BUILTIN_THEME','Duplicate a built-in theme before editing.');const validation=validateTheme(raw,true);if(!validation.config||validation.errors.some(error=>error.section!=='colors'))throw new LifecycleError('INVALID_THEME','Theme draft is invalid.',validation);const config=validation.config;db.prepare("UPDATE presentation_themes SET name=?,description=?,draft_json=?,status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(config.metadata.name,config.metadata.description,JSON.stringify(config),id);return getDesignerTheme(id)}
export function revertThemeDraft(id:string){const theme=row(id);if(!theme)throw new LifecycleError('THEME_NOT_FOUND','Theme not found.');if(theme.is_builtin)throw new LifecycleError('BUILTIN_THEME','Built-in themes have no editable draft.');db.prepare("UPDATE presentation_themes SET draft_json=published_json,status='published',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(id);return getDesignerTheme(id)}
export function publishTheme(id:string,input:any={}){const theme=row(id);if(!theme)throw new LifecycleError('THEME_NOT_FOUND','Theme not found.');if(theme.is_builtin)throw new LifecycleError('BUILTIN_THEME','Duplicate a built-in theme before publishing changes.');const config=normalizeThemeConfig(theme.draft_json,theme.name),validation=validateTheme(config,Boolean(input.confirmSevereContrast));if(!validation.valid)throw new LifecycleError('INVALID_THEME','Theme cannot be published.',validation);const version=Number(theme.published_version??0)+1,parent:any=db.prepare('SELECT id FROM theme_versions WHERE theme_id=? AND active_published=1 ORDER BY version_number DESC LIMIT 1').get(id),versionId=crypto.randomUUID(),json=JSON.stringify(config);db.exec('BEGIN');try{db.prepare('UPDATE theme_versions SET active_published=0 WHERE theme_id=?').run(id);db.prepare('INSERT INTO theme_versions(id,theme_id,version_number,config_json,created_by,change_summary,parent_version_id,active_published,published_at) VALUES(?,?,?,?,?,?,?,1,CURRENT_TIMESTAMP)').run(versionId,id,version,json,String(input.createdBy??'Local host').slice(0,80),String(input.changeSummary??'Published theme changes').slice(0,500),parent?.id??null);db.prepare("UPDATE presentation_themes SET config_json=?,published_json=?,draft_json=?,status='published',revision=revision+1,published_version=?,published_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(json,json,json,version,id);db.exec('COMMIT')}catch(error){db.exec('ROLLBACK');throw error}return getDesignerTheme(id)}
export function listThemeVersions(id:string){return(db.prepare('SELECT id,theme_id,version_number,created_by,change_summary,parent_version_id,active_published,created_at,published_at FROM theme_versions WHERE theme_id=? ORDER BY version_number DESC').all(id)as any[]).map(value=>({...value,activePublished:Boolean(value.active_published)}))}
export function restoreThemeVersion(id:string,versionId:string){const theme=row(id),version:any=db.prepare('SELECT config_json FROM theme_versions WHERE id=? AND theme_id=?').get(versionId,id);if(!theme||!version)throw new LifecycleError('VERSION_NOT_FOUND','Theme version not found.');if(theme.is_builtin)throw new LifecycleError('BUILTIN_THEME','Duplicate a built-in theme before restoring versions.');db.prepare("UPDATE presentation_themes SET draft_json=?,status='draft',updated_at=CURRENT_TIMESTAMP WHERE id=?").run(version.config_json,id);return getDesignerTheme(id)}
export function deleteDesignerTheme(id:string){const theme=row(id);if(!theme)throw new LifecycleError('THEME_NOT_FOUND','Theme not found.');if(theme.is_builtin)throw new LifecycleError('BUILTIN_THEME','Built-in themes cannot be deleted.');if(db.prepare('SELECT 1 FROM presentation_state WHERE theme_id=? LIMIT 1').get(id))throw new LifecycleError('THEME_IN_USE','Remove this theme from active episodes before deleting it.');db.prepare('DELETE FROM presentation_themes WHERE id=?').run(id)}
export function exportTheme(id:string){const theme=getDesignerTheme(id);return{compatibilityVersion:1,exportedAt:new Date().toISOString(),theme:{name:theme.name,description:theme.description,config:theme.draft},versions:theme.versions}}
export function inspectThemeImport(input:any){if(input?.compatibilityVersion!==1)throw new LifecycleError('INCOMPATIBLE_THEME','Unsupported theme compatibility version.');const validation=validateTheme(input?.theme?.config,true),missingAssets=validation.config?.assetReferences.filter(ref=>!db.prepare('SELECT 1 FROM presentation_assets WHERE id=? AND active=1').get(ref.assetId)).map(ref=>ref.assetId)??[];return{...validation,missingAssets,name:String(input?.theme?.name??validation.config?.metadata.name??'Imported Theme').slice(0,100)}}
export function importTheme(input:any){const inspected=inspectThemeImport(input);if(!inspected.config||inspected.errors.some(error=>error.section!=='assets'))throw new LifecycleError('INVALID_THEME','Imported theme is invalid.',inspected);const config=structuredClone(inspected.config);config.assetReferences=config.assetReferences.filter(ref=>!inspected.missingAssets.includes(ref.assetId));for(const key of ['logoAssetId','watermarkAssetId','sponsorAssetId']as const)if(config.branding[key]&&inspected.missingAssets.includes(config.branding[key]!))config.branding[key]=null;return createTheme({name:`${inspected.name} Import`,config})}
export function issuePreviewToken(id:string){getDesignerTheme(id);const token=crypto.randomBytes(32).toString('base64url');db.prepare('DELETE FROM theme_preview_tokens WHERE expires_at<CURRENT_TIMESTAMP').run();db.prepare('INSERT INTO theme_preview_tokens(token_hash,theme_id,expires_at) VALUES(?,?,?)').run(hash(token),id,new Date(Date.now()+2*60*60*1000).toISOString());return{token,expiresAt:new Date(Date.now()+2*60*60*1000).toISOString()}}
export function previewTheme(id:string,token?:string){const theme=getDesignerTheme(id);if(token){const valid=db.prepare('SELECT 1 FROM theme_preview_tokens WHERE token_hash=? AND theme_id=? AND expires_at>CURRENT_TIMESTAMP').get(hash(token),id);if(!valid)throw new LifecycleError('INVALID_PREVIEW_TOKEN','Preview token is invalid or expired.');return{themeId:id,preview:true,config:theme.draft}}return{themeId:id,preview:true,config:theme.published}}

export function exportThemeDesignerBackup(){return{versions:db.prepare('SELECT * FROM theme_versions').all(),presets:db.prepare('SELECT * FROM theme_presets').all()}}
export function restoreThemeDesignerBackup(data:any){if(!data)return;for(const[table,rows]of[['theme_versions',data.versions??[]],['theme_presets',data.presets??[]]]as const)for(const item of rows){const keys=Object.keys(item);db.prepare(`INSERT OR REPLACE INTO ${table}(${keys.join(',')}) VALUES(${keys.map(()=>'?').join(',')})`).run(...keys.map(key=>item[key]))}}
