import{test,expect}from'@playwright/test';
test('question lifecycle, persistence, backup/restore, and episode workflow',async({page,request})=>{
 test.setTimeout(45_000);
 const acceptDialog=async(action:()=>Promise<unknown>,text?:string)=>{const dialogPromise=page.waitForEvent('dialog');const actionPromise=action();const dialog=await dialogPromise;await dialog.accept(text);await actionPromise};
 const id=`E2E-${Date.now()}`;await page.goto('/');
 await page.getByRole('button',{name:'New question'}).click();await page.getByLabel('ID',{exact:true}).fill(id);await page.getByLabel('Category',{exact:true}).fill('E2E Category');await page.getByLabel('Question',{exact:true}).fill('Original E2E question');await page.getByLabel('Correct answer',{exact:true}).fill('Original answer');await page.getByRole('button',{name:'Save question'}).click();
 await page.getByLabel('Search questions').fill(id);await expect(page.locator('main > p')).toHaveText('1 questions');let row=page.getByRole('row').filter({hasText:id});await row.getByRole('button',{name:'Edit'}).click();const modal=page.locator('.modal');await expect(modal).toBeVisible();await modal.locator('textarea').first().fill('Edited E2E question');await modal.getByRole('button',{name:'Save question'}).click();row=page.getByRole('row').filter({hasText:id});await expect(row).toContainText('Edited E2E question');
 await acceptDialog(()=>row.getByRole('button',{name:'Duplicate'}).click(),`${id}-COPY`);await page.getByLabel('Search questions').fill(`${id}-COPY`);await expect(page.locator('main > p')).toHaveText('1 questions');let copyRow=page.getByRole('row').filter({hasText:`${id}-COPY`});
 await page.reload();await page.getByLabel('Search questions').fill(`${id}-COPY`);await expect(page.locator('main > p')).toHaveText('1 questions');copyRow=page.getByRole('row').filter({hasText:`${id}-COPY`});await expect(copyRow).toContainText('Edited E2E question');
 await expect(page.getByLabel('Filter category').locator('option')).toHaveCount(8);const csvExport=await request.get('/api/questions/export.csv');expect(csvExport.ok()).toBeTruthy();const csvText=await csvExport.text();expect(csvText).toContain('SAMPLE-001');expect(csvText).toContain(`${id}-COPY`);
 const invalidCsv='id,category,difficulty,questionText,correctAnswer\nBAD,,9,,\n';await page.locator('input[accept=".csv"]').setInputFiles({name:'invalid.csv',mimeType:'text/csv',buffer:Buffer.from(invalidCsv)});await expect(page.locator('.error')).toContainText('Row 2:');
 const backup=await request.get('/api/backup');expect(backup.ok()).toBeTruthy();const backupData=await backup.json();expect(backupData.questions.length).toBeGreaterThanOrEqual(62);
 await page.getByRole('button',{name:'New Episode'}).click();await page.getByLabel('Recent use').selectOption('allow-all');await page.getByRole('button',{name:'Generate board'}).click();await expect(page.locator('.board-column')).toHaveCount(4);for(const column of await page.locator('.board-column').all())await expect(column.locator('article')).toHaveCount(5);
 await acceptDialog(()=>page.getByRole('button',{name:'Save draft'}).click());await acceptDialog(()=>page.getByRole('button',{name:'Save and lock'}).click());
 await page.getByRole('button',{name:'Question Library'}).click();await page.getByLabel('Search questions').fill(`${id}-COPY`);await expect(page.locator('main > p')).toHaveText('1 questions');copyRow=page.getByRole('row').filter({hasText:`${id}-COPY`});await acceptDialog(()=>copyRow.getByRole('button',{name:'Delete'}).click());await expect(page.locator('main > p')).toHaveText('0 questions');
 const restore=await request.post('/api/restore',{data:backupData});expect(restore.ok()).toBeTruthy();await page.reload();await page.getByLabel('Search questions').fill(`${id}-COPY`);await expect(page.locator('main > p')).toHaveText('1 questions');copyRow=page.getByRole('row').filter({hasText:`${id}-COPY`});await expect(copyRow).toContainText('Edited E2E question');
 await acceptDialog(()=>copyRow.getByRole('button',{name:'Delete'}).click());await page.getByLabel('Search questions').fill(id);await expect(page.locator('main > p')).toHaveText('1 questions');row=page.getByRole('row').filter({hasText:id});await acceptDialog(()=>row.getByRole('button',{name:'Delete'}).click());
});
