import { useEffect, useMemo, useState } from 'react';
import type { PresentationLayout,PublicLiveState } from '../../shared/types';
import { PresentationRenderer } from '../components/PresentationRenderer';
import { useLiveState } from '../useLiveState';

const validLayouts=new Set(['full','overlay','scorebug','question','lowerthird']);
function useCountdown(state:PublicLiveState|null){const[,tick]=useState(0);useEffect(()=>{if(state?.timer.status!=='running')return;const id=setInterval(()=>tick(value=>value+1),250);return()=>clearInterval(id)},[state?.timer.status,state?.timer.resumedAt]);if(!state)return 0;return state.timer.status==='running'?Math.max(0,state.timer.remainingMs-(Date.now()-Date.parse(state.timer.serverNow))):state.timer.remainingMs}
function cueTone(type:string,muted:boolean){if(muted)return;try{const Audio=window.AudioContext||(window as any).webkitAudioContext,context=new Audio(),oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=type.includes('winner')?784:type.includes('answer')?660:type.includes('d20')?440:520;gain.gain.value=.055;oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.18)}catch{/* OBS autoplay may require interaction */}}
export function AudienceDisplay({id}:{id:string}){const{state,connected}=useLiveState<PublicLiveState>(id,'audience'),remaining=useCountdown(state),[hiddenRoll,setHiddenRoll]=useState<string|null>(null),params=useMemo(()=>new URLSearchParams(location.hash.split('?')[1]??location.search),[]);useEffect(()=>{const cue=state?.presentation.audio.cue;if(cue)cueTone(cue.type,params.get('audio')==='off'||Boolean(state?.presentation.audio.masterMuted)||Boolean(state?.presentation.audio.reducedAudio))},[state?.presentation.audio.cue?.id]);if(!state)return <div className="audience standby"><h1>Geek Trivia Live</h1><p>{connected?'Preparing the show…':'Reconnecting…'}</p></div>;const presentation=state.presentation,requested=params.get('layout'),layout=(validLayouts.has(requested??'')?requested:presentation.layout)as PresentationLayout,reduced=params.get('reducedMotion')==='true'||presentation.reducedMotion,showD20=presentation.programScene==='d20'&&Boolean(state.d20)&&hiddenRoll!==state.d20?.rolledAt;return <PresentationRenderer state={state} presentation={presentation} layout={layout} remainingMs={remaining} connected={connected} reduced={reduced} showD20={showD20} onD20Done={()=>state.d20&&setHiddenRoll(state.d20.rolledAt)}/>}
