import { useEffect, useMemo, useState } from "react";
import type { PresentationLayout, PublicLiveState } from "../../shared/types.js";
import { useLiveState } from "../useLiveState.js";
import { D20Presentation } from "../components/D20Presentation.js";

const validLayouts=new Set(["full","overlay","scorebug","question","lowerthird"]);
function useCountdown(state:PublicLiveState|null){const[,tick]=useState(0);useEffect(()=>{if(state?.timer.status!=="running")return;const id=setInterval(()=>tick(x=>x+1),250);return()=>clearInterval(id)},[state?.timer.status,state?.timer.resumedAt]);if(!state)return 0;return state.timer.status==="running"?Math.max(0,state.timer.remainingMs-(Date.now()-Date.parse(state.timer.serverNow))):state.timer.remainingMs}
function cueTone(type:string,muted:boolean){if(muted)return;try{const Audio=window.AudioContext||(window as any).webkitAudioContext,ctx=new Audio(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=type.includes('winner')?784:type.includes('answer')?660:type.includes('d20')?440:520;gain.gain.value=.055;osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.18)}catch{/* OBS autoplay may require interaction */}}
function Scores({state,compact=false}:{state:PublicLiveState;compact?:boolean}){const top=state.participants[0]?.score;return <ol className={compact?"score-bug":"standings"}>{state.participants.map((p,i)=><li key={p.displayName} className={p.score===top?'leader':''}><span>{p.placement??i+1}. {p.displayName}{p.score===top&&<em> leader</em>}</span><strong>{p.score} XP</strong></li>)}</ol>}
export function AudienceDisplay({id}:{id:string}){const{state,connected}=useLiveState<PublicLiveState>(id,"audience"),remaining=useCountdown(state),[hiddenRoll,setHiddenRoll]=useState<string|null>(null),params=useMemo(()=>new URLSearchParams(location.hash.split('?')[1]??location.search),[]);useEffect(()=>{const cue=state?.presentation.audio.cue;if(cue)cueTone(cue.type,params.get('audio')==='off'||Boolean(state?.presentation.audio.masterMuted)||Boolean(state?.presentation.audio.reducedAudio))},[state?.presentation.audio.cue?.id]);if(!state)return <div className="audience standby"><h1>Geek Trivia Live</h1><p>{connected?"Preparing the show…":"Reconnecting…"}</p></div>;
 const p=state.presentation,requested=params.get('layout'),layout=(validLayouts.has(requested??'')?requested:p.layout)as PresentationLayout,audioDisabled=params.get('audio')==='off',reduced=params.get('reducedMotion')==='true'||p.reducedMotion,showD20=p.programScene==='d20'&&state.d20&&hiddenRoll!==state.d20.rolledAt;
 const vars={"--primary":p.theme.colors.primary,"--secondary":p.theme.colors.secondary,"--background":p.theme.colors.background,"--surface":p.theme.colors.surface,"--accent":p.theme.colors.accent,"--text":p.theme.colors.text,"--muted":p.theme.colors.muted,"--success":p.theme.colors.success,"--warning":p.theme.colors.warning,"--error":p.theme.colors.error,"--font-display":p.theme.fonts.display,"--font-heading":p.theme.fonts.heading,"--font-body":p.theme.fonts.body,"--font-score":p.theme.fonts.score,"--font-timer":p.theme.fonts.timer,"--font-question":p.theme.fonts.question,"--radius":p.theme.shape.radius,"--transition-ms":`${reduced||p.animationsDisabled?0:p.transition.durationMs}ms`,"--title-safe":`${p.safeArea.titleSafePercent}%`,"--action-safe":`${p.safeArea.actionSafePercent}%`}as React.CSSProperties;
 const scene=p.programScene;
 return <div style={vars} className={`audience presentation theme-${p.theme.id} layout-${layout} scene-${scene} transition-${reduced||p.animationsDisabled?p.transition.reducedMotionFallback:p.transition.kind} ${reduced?'reduced-motion':''}`} aria-live="polite">
  <header className="program-brand"><div>{p.profile.logoUrl?<img src={p.profile.logoUrl} alt={`${p.profile.name} logo`}/>:<span className="logo-placeholder">NW</span>}<h1>{p.profile.showTitle}</h1></div><span className="audience-connection">{connected?'LIVE':'Reconnecting…'}</span></header>
  <main className="program-stage" key={`${scene}-${p.transition.startedAt??''}`}>
   {showD20?<D20Presentation roll={state.d20!} onDone={()=>setHiddenRoll(state.d20!.rolledAt)}/>:<>
    {scene==='standby'&&<section className="hero-scene"><p className="eyebrow">{p.profile.subtitle}</p><h2>Stand by</h2><p>The show begins soon</p></section>}
    {scene==='intro'&&<section className="hero-scene intro-scene"><p className="eyebrow">Live game show</p><h2>{p.profile.showTitle}</h2><p>{state.title}</p></section>}
    {scene==='board'&&<section className={`audience-board categories-${state.board.length}`}>{state.board.map((c,ci)=><article key={c.name} style={{"--category-index":ci}as React.CSSProperties}><h2 title={c.name}>{c.name}</h2>{c.squares.map(q=><div className={`audience-square state-${q.status} ${q.active?'active':''}`} key={q.key}>{['completed','skipped'].includes(q.status)?<span>{q.status}</span>:<strong>{q.value}</strong>}</div>)}</article>)}</section>}
    {scene==='question'&&state.question&&<section className="broadcast-question"><p className="question-meta">{state.question.category} · {state.question.value} XP</p><h2 className={state.question.text.length>180?'long-copy':''}>{state.question.text}</h2><output className={`broadcast-timer ${state.timer.status}`}>{Math.ceil(remaining/1000)}</output>{state.d20&&<aside className="modifier-banner">{state.d20.effectName}</aside>}</section>}
    {scene==='answer'&&state.question&&<section className="broadcast-question answer-scene"><p>{state.question.category} · {state.question.value} XP</p><h2>{state.question.text}</h2>{state.question.answer&&<div className="answer-reveal"><span>Correct answer</span><strong>{state.question.answer}</strong></div>}</section>}
    {scene==='scores'&&<section className="hero-scene"><h2>Scores</h2><Scores state={state}/></section>}
    {scene==='intermission'&&<section className="hero-scene"><p className="eyebrow">Intermission</p><h2>Be right back</h2><Scores state={state} compact/></section>}
    {(scene==='winner'||scene==='final')&&<section className="hero-scene winner-scene"><div className="confetti" aria-hidden="true">◆ ✦ ▲ ● ◆ ✦</div><p className="eyebrow">{scene==='winner'?'Winner':'Final standings'}</p><h2>{state.participants.filter(x=>x.score===state.participants[0]?.score).map(x=>x.displayName).join(' & ')||'Thanks for playing!'}</h2><Scores state={state}/></section>}
    {scene==='credits'&&<section className="hero-scene credits-scene"><h2>Credits</h2><p>Hosted with {p.profile.showTitle}</p><p>Players: {state.participants.map(x=>x.displayName).join(', ')||'Our trivia community'}</p><p>Questions and production: Geek Trivia Live</p></section>}
    {scene==='round-transition'&&<section className="hero-scene"><p className="eyebrow">Next round</p><h2>Get ready</h2></section>}
    {scene==='custom-message'&&<section className="hero-scene"><h2>{p.customMessage??'Stay tuned'}</h2></section>}
   </>}
  </main>
  {(layout==='scorebug'||layout==='overlay')&&<aside className="overlay-score"><Scores state={state} compact/><output>{Math.ceil(remaining/1000)}s</output></aside>}
  {layout==='lowerthird'&&<aside className="lower-third"><strong>{p.customMessage??state.question?.category??p.profile.showTitle}</strong><span>{p.profile.subtitle}</span></aside>}
  {p.graphics.map(g=><aside className={`broadcast-graphic graphic-${g.type}`} key={g.id}>{g.text}</aside>)}
  {p.profile.watermarkUrl&&<img className="program-watermark" src={p.profile.watermarkUrl} alt=""/>}
  {p.safeArea.showGuides&&<div className="safe-guides rehearsal-only"><div className="action-safe"/><div className="title-safe"/>{p.safeArea.cameraZones.map(z=><i key={z.id} style={{left:`${z.x}%`,top:`${z.y}%`,width:`${z.width}%`,height:`${z.height}%`}}/>)}</div>}
  {layout==='full'&&<footer>{state.participants.map(p=><div key={p.displayName}><span>{p.displayName}</span><strong>{p.score}</strong></div>)}</footer>}
 </div>}
