import{useEffect,useRef,useState}from'react';import type{ContestantProjection}from'../../shared/types';
const key='geek-trivia-contestant-token';
export function ContestantPlay({joinCode}:{joinCode?:string}){const[token,setToken]=useState(()=>localStorage.getItem(key)??''),[state,setState]=useState<ContestantProjection|null>(null),[code,setCode]=useState(joinCode??''),[name,setName]=useState(''),[team,setTeam]=useState(''),[pin,setPin]=useState(''),[error,setError]=useState(''),[muted,setMuted]=useState(false),socket=useRef<WebSocket|null>(null),sequence=useRef(0);
 useEffect(()=>{if(!token)return;const protocol=location.protocol==='https:'?'wss':'ws',ws=new WebSocket(`${protocol}://${location.host}/ws?role=contestant&sessionToken=${encodeURIComponent(token)}`);socket.current=ws;ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.event==='state.contestant')setState(m.data);if(m.event==='command.rejected')setError(m.data.message)};ws.onclose=()=>setError('Connection lost. Reconnecting…');return()=>ws.close()},[token]);
 const join=async()=>{setError('');const r=await fetch('/api/contestant/join',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({joinCode:code,displayName:name,teamName:team||undefined,pin:pin||undefined})}),body=await r.json();if(!r.ok){setError(body.error??'Unable to join.');return}localStorage.setItem(key,body.token);setToken(body.token);setState(body.state)};
 const send=(type:string,extra:Record<string,unknown>={})=>socket.current?.send(JSON.stringify({type,...extra}));
 const buzz=()=>{if(!state?.buzzer.id||!state.buzzer.eligible)return;sequence.current++;send('contestant.buzz',{commandId:crypto.randomUUID(),buzzerSessionId:state.buzzer.id,expectedRevision:state.buzzer.revision,clientSequence:sequence.current,clientTimestamp:new Date().toISOString()});if(!muted)try{navigator.vibrate?.(60)}catch{}}
 useEffect(()=>{const press=(e:KeyboardEvent)=>{if((e.code==='Space'||e.code==='Enter')&&state?.buzzer.eligible){e.preventDefault();buzz()}};addEventListener('keydown',press);return()=>removeEventListener('keydown',press)},[state]);
 if(!token||!state)return <main className="contestant-app"><section className="join-card"><p className="eyebrow">Geek Trivia Live</p><h1>Join the game</h1><label>Join code<input autoCapitalize="characters" value={code} onChange={e=>setCode(e.target.value.toUpperCase())} maxLength={12}/></label><label>Display name<input value={name} onChange={e=>setName(e.target.value)} maxLength={40}/></label><label>Team (optional)<input value={team} onChange={e=>setTeam(e.target.value)} maxLength={40}/></label><label>PIN (if required)<input type="password" value={pin} onChange={e=>setPin(e.target.value)} maxLength={20}/></label><button className="join-button" disabled={!code||!name.trim()} onClick={join}>Join show</button>{error&&<div role="alert" className="error">{error}</div>}</section></main>;
 const label=state.buzzer.result==='won'?'You buzzed first':state.buzzer.result==='locked-out'?'Another contestant buzzed first':state.buzzer.result==='correct'?'Correct!':state.buzzer.result==='incorrect'?'Incorrect':state.buzzer.eligible?'BUZZ':'Get ready';
 return <main className={`contestant-app contestant-${state.buzzer.result}`}><header><div><p className="eyebrow">{state.showTitle}</p><h1>{state.displayName}</h1><p>{state.team??'Individual player'} · {state.score} XP</p></div><span className={state.connected?'online':'offline'}>{state.connected?'Connected':'Reconnecting'}</span></header><section className="contestant-status" aria-live="assertive"><p>{state.question?`${state.question.category} · ${state.question.value} XP`:'Waiting for host'}</p>{state.question?.text&&<h2>{state.question.text}</h2>}<button className="buzzer-button" disabled={!state.buzzer.eligible} onClick={buzz}>{label}</button><p>{state.buzzer.state.replace('-',' ')}</p></section><footer><button onClick={()=>send(state.ready?'contestant.notReady':'contestant.ready')}>{state.ready?'Not ready':'Ready'}</button><button onClick={()=>setMuted(x=>!x)}>{muted?'Audio off':'Audio on'}</button></footer>{error&&<div role="alert" className="error">{error}</div>}</main>}
