import type { CSSProperties } from 'react';
import { themeCssVariables, type ThemeConfig, type ThemePosition } from '../../shared/themeDesigner';
import type { PresentationLayout, PresentationScene, PublicLiveState, PublicPresentationState } from '../../shared/types';
import { D20Presentation } from './D20Presentation';

const positionStyle=(position?:ThemePosition):CSSProperties|undefined=>position?{position:'absolute',left:`${position.x}%`,top:`${position.y}%`,width:`${position.width}%`,height:`${position.height}%`,zIndex:position.zIndex,display:position.hidden?'none':undefined}:undefined;
const selectedPosition=(config:ThemeConfig|undefined,scene:PresentationScene,layout:PresentationLayout,key:string)=>config?.scenes[scene]?.positions[key]??config?.layouts[layout]?.positions[key];
export function themeVariables(p:PublicPresentationState,reduced=false):CSSProperties{const base={'--primary':p.theme.colors.primary,'--secondary':p.theme.colors.secondary,'--background':p.theme.colors.background,'--surface':p.theme.colors.surface,'--accent':p.theme.colors.accent,'--text':p.theme.colors.text,'--muted':p.theme.colors.muted,'--success':p.theme.colors.success,'--warning':p.theme.colors.warning,'--error':p.theme.colors.error,'--font-display':p.theme.fonts.display,'--font-heading':p.theme.fonts.heading,'--font-body':p.theme.fonts.body,'--font-score':p.theme.fonts.score,'--font-timer':p.theme.fonts.timer,'--font-question':p.theme.fonts.question,'--radius':p.theme.shape.radius,'--transition-ms':`${reduced||p.animationsDisabled?0:p.transition.durationMs}ms`,'--title-safe':`${p.safeArea.titleSafePercent}%`,'--action-safe':`${p.safeArea.actionSafePercent}%`}as CSSProperties;return{...base,...(p.theme.designer?themeCssVariables(p.theme.designer):{})}as CSSProperties}
function Scores({state,compact=false}:{state:PublicLiveState;compact?:boolean}){const top=state.participants[0]?.score;return <ol className={compact?'score-bug':'standings'}>{state.participants.map((participant,index)=><li key={participant.displayName} className={participant.score===top?'leader':''}><span>{participant.placement??index+1}. {participant.displayName}{participant.score===top&&<em> leader</em>}</span><strong>{participant.score} XP</strong></li>)}</ol>}

export function PresentationRenderer({state,presentation=pState(state),scene=presentation.programScene,layout=presentation.layout,remainingMs=state.timer.remainingMs,connected=true,reduced=false,preview=false,showD20=true,onD20Done}:{state:PublicLiveState;presentation?:PublicPresentationState;scene?:PresentationScene;layout?:PresentationLayout;remainingMs?:number;connected?:boolean;reduced?:boolean;preview?:boolean;showD20?:boolean;onD20Done?:()=>void}){
 const p=presentation,config=p.theme.designer,displayD20=showD20&&scene==='d20'&&state.d20;
 const pos=(key:string)=>positionStyle(selectedPosition(config,scene,layout,key));
 return <div style={themeVariables(p,reduced)} className={`audience presentation theme-${p.theme.id} layout-${layout} scene-${scene} transition-${reduced||p.animationsDisabled?p.transition.reducedMotionFallback:p.transition.kind} ${reduced?'reduced-motion':''} ${preview?'theme-preview-canvas':''}`} aria-live="polite">
  <header className="program-brand" style={pos('logo')}><div>{p.profile.logoUrl?<img src={p.profile.logoUrl} alt={`${p.profile.name} logo`}/>:<span className="logo-placeholder">NW</span>}<h1>{p.profile.showTitle}</h1></div><span className="audience-connection">{preview?'PREVIEW':connected?'LIVE':'Reconnecting…'}</span></header>
  <main className="program-stage" key={`${scene}-${p.transition.startedAt??''}`}>
   {displayD20?<div style={pos('d20')}><D20Presentation roll={state.d20!} onDone={onD20Done??(()=>{})}/></div>:<>
    {scene==='standby'&&<section className="hero-scene"><p className="eyebrow">{p.profile.subtitle}</p><h2>Stand by</h2><p>The show begins soon</p></section>}
    {scene==='intro'&&<section className="hero-scene intro-scene"><p className="eyebrow">Live game show</p><h2>{p.profile.showTitle}</h2><p>{state.title}</p></section>}
    {scene==='board'&&<section style={pos('board')} className={`audience-board categories-${state.board.length}`}>{state.board.map((category,index)=><article key={category.name} style={{'--category-index':index}as CSSProperties}><h2 title={category.name}>{category.name}</h2>{category.squares.map(question=><div className={`audience-square state-${question.status} ${question.active?'active':''}`} key={question.key}>{['completed','skipped'].includes(question.status)?<span>{config?.board.usedText??question.status}</span>:<strong>{question.value}</strong>}</div>)}</article>)}</section>}
    {scene==='question'&&state.question&&<section style={pos('question')} className="broadcast-question"><p className="question-meta">{state.question.category} · {state.question.value} XP</p><h2 className={state.question.text.length>180?'long-copy':''}>{state.question.text}</h2><output style={pos('timer')} className={`broadcast-timer ${state.timer.status}`}>{Math.ceil(remainingMs/1000)}</output>{state.d20&&<aside className="modifier-banner">{state.d20.effectName}</aside>}</section>}
    {scene==='answer'&&state.question&&<section style={pos('question')} className="broadcast-question answer-scene">{config?.answer.showQuestion!==false&&<><p>{state.question.category} · {state.question.value} XP</p><h2>{state.question.text}</h2></>}{state.question.answer&&<div className="answer-reveal"><span>{config?.answer.label??'Correct answer'}</span><strong>{state.question.answer}</strong></div>}</section>}
    {scene==='scores'&&<section style={pos('scoreboard')} className="hero-scene"><h2>Scores</h2><Scores state={state}/></section>}
    {scene==='intermission'&&<section className="hero-scene"><p className="eyebrow">Intermission</p><h2>Be right back</h2><Scores state={state} compact/></section>}
    {(scene==='winner'||scene==='final')&&<section className="hero-scene winner-scene"><div className="confetti" aria-hidden="true">◆ ✦ ▲ ● ◆ ✦</div><p className="eyebrow">{scene==='winner'?'Winner':'Final standings'}</p><h2>{state.participants.filter(item=>item.score===state.participants[0]?.score).map(item=>item.displayName).join(' & ')||'Thanks for playing!'}</h2><Scores state={state}/></section>}
    {scene==='credits'&&<section className="hero-scene credits-scene"><h2>Credits</h2><p>Hosted with {p.profile.showTitle}</p><p>Players: {state.participants.map(item=>item.displayName).join(', ')||'Our trivia community'}</p><p>Questions and production: Geek Trivia Live</p></section>}
    {scene==='round-transition'&&<section className="hero-scene"><p className="eyebrow">Next round</p><h2>Get ready</h2></section>}
    {scene==='custom-message'&&<section className="hero-scene"><h2>{p.customMessage??'Stay tuned'}</h2></section>}
   </>}
  </main>
  {(layout==='scorebug'||layout==='overlay')&&<aside style={pos('scoreboard')} className="overlay-score"><Scores state={state} compact/><output>{Math.ceil(remainingMs/1000)}s</output></aside>}
  {layout==='lowerthird'&&<aside style={pos('lowerThird')} className="lower-third"><strong>{p.customMessage??state.question?.category??p.profile.showTitle}</strong><span>{p.profile.subtitle}</span></aside>}
  {p.graphics.map(graphic=><aside className={`broadcast-graphic graphic-${graphic.type}`} key={graphic.id}>{graphic.text}</aside>)}
  {p.profile.watermarkUrl&&<img style={pos('watermark')} className="program-watermark" src={p.profile.watermarkUrl} alt=""/>}
  {p.safeArea.showGuides&&<div className="safe-guides rehearsal-only"><div className="action-safe"/><div className="title-safe"/>{p.safeArea.cameraZones.map(zone=><i key={zone.id} style={{left:`${zone.x}%`,top:`${zone.y}%`,width:`${zone.width}%`,height:`${zone.height}%`}}/>)}</div>}
  {layout==='full'&&<footer>{state.participants.map(participant=><div key={participant.displayName}><span>{participant.displayName}</span><strong>{participant.score}</strong></div>)}</footer>}
 </div>
}
function pState(state:PublicLiveState){return state.presentation}
