import type { FormEvent } from 'react'; import type { Question } from '../../shared/types';
export const blankQuestion=():Question=>({id:'',category:'',subcategory:'',difficulty:1,pointValue:100,questionText:'',correctAnswer:'',alternateAnswers:[],questionType:'text',mediaPath:null,hostNotes:'',source:'',active:true,usedCount:0,dateLastUsed:null,episodeLastUsed:null});
export function QuestionForm({value,onChange,onSubmit,onCancel}:{value:Question;onChange:(q:Question)=>void;onSubmit:()=>void;onCancel:()=>void}){
 const set=<K extends keyof Question>(key:K,v:Question[K])=>onChange({...value,[key]:v}); const submit=(e:FormEvent)=>{e.preventDefault();onSubmit()};
 return <form className="editor" onSubmit={submit}><h2>{value.id?'Edit question':'New question'}</h2>
  <div className="form-grid"><label>ID<input required value={value.id} onChange={e=>set('id',e.target.value)}/></label><label>Category<input required value={value.category} onChange={e=>set('category',e.target.value)}/></label><label>Franchise / subcategory<input value={value.subcategory} onChange={e=>set('subcategory',e.target.value)}/></label><label>Difficulty<select value={value.difficulty} onChange={e=>{const d=Number(e.target.value) as Question['difficulty'];onChange({...value,difficulty:d,pointValue:d*100})}}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>XP<input readOnly value={value.difficulty*100}/></label><label>Active<select value={String(value.active)} onChange={e=>set('active',e.target.value==='true')}><option value="true">Active</option><option value="false">Inactive</option></select></label></div>
  <label>Question<textarea required value={value.questionText} onChange={e=>set('questionText',e.target.value)}/></label><label>Correct answer<input required value={value.correctAnswer} onChange={e=>set('correctAnswer',e.target.value)}/></label><label>Alternate answers (one per line)<textarea value={value.alternateAnswers.join('\n')} onChange={e=>set('alternateAnswers',e.target.value.split('\n').map(x=>x.trim()).filter(Boolean))}/></label><label>Optional media path<input value={value.mediaPath??''} onChange={e=>set('mediaPath',e.target.value||null)}/></label><label>Host notes<textarea value={value.hostNotes} onChange={e=>set('hostNotes',e.target.value)}/></label><label>Source<input value={value.source} onChange={e=>set('source',e.target.value)}/></label><div className="actions"><button type="submit">Save question</button><button type="button" className="secondary" onClick={onCancel}>Cancel</button></div>
 </form>;
}
