import './migrate.js'; import { db } from './database.js';
const categories = [
  ['Star Voyagers','Cosmic Trek'], ['Arcane Academy','Wizard School'], ['Pixel Realms','Retro Games'],
  ['Cape Chronicles','Comic Heroes'], ['Robot Uprising','Science Fiction'], ['Mythic Quests','Fantasy Adventures']
];
const insert = db.prepare(`INSERT OR IGNORE INTO questions(id,category,subcategory,difficulty,point_value,question_text,correct_answer,alternate_answers,question_type,host_notes,source) VALUES(?,?,?,?,?,?,?,?,?,?,?)`);
db.exec('BEGIN'); try { for (const [ci,[category, franchise]] of categories.entries()) for (let d=1; d<=5; d++) for (let variant=1; variant<=2; variant++) { const n=ci*10+(d-1)*2+variant; insert.run(`SAMPLE-${String(n).padStart(3,'0')}`,category,franchise,d,d*100,`Sample ${category} difficulty ${d}, variant ${variant}: replace with a researched question.`,`Sample answer ${n}`,JSON.stringify([`Alternate ${n}`]),'text','DEVELOPMENT SAMPLE — verify before broadcast.','Geek Trivia Live sample data'); }
 const options=JSON.stringify({categoryCount:4,seed:'demo-phase-2',recentUsePolicy:{mode:'allow-all'},manualCategories:categories.slice(0,4).map(c=>c[0])});const demos=[['DEMO-EP-DRAFT','DEMO — Draft Episode','draft'],['DEMO-EP-LOCKED','DEMO — Locked Episode','locked'],['DEMO-EP-RUN','DEMO — In-Progress Episode','in_progress'],['DEMO-EP-COMPLETE','DEMO — Completed Episode','completed']] as const;const addEpisode=db.prepare(`INSERT OR IGNORE INTO episodes(id,title,seed,category_count,status,options_json,episode_number,scheduled_date,started_at,completed_at,usage_accounted_at,final_winner) VALUES(?,?,?,4,?,?,?,date('now'),?,?,?,?)`);const addBoard=db.prepare('INSERT OR IGNORE INTO episode_questions(episode_id,question_id,category_position,difficulty,state,opened_at,completed_at,outcome) VALUES(?,?,?,?,?,?,?,?)');for(const[id,title,status]of demos){const completed=status==='completed',running=status==='in_progress';const result=addEpisode.run(id,title,'demo-phase-2',status,options,id.replace('DEMO-EP-',''),running||completed?new Date().toISOString():null,completed?new Date().toISOString():null,completed?new Date().toISOString():null,completed?'Ada':null);for(let c=0;c<4;c++)for(let d=1;d<=5;d++){const qid=`SAMPLE-${String(c*10+(d-1)*2+1).padStart(3,'0')}`;const finalized=completed||(running&&c===0&&d<=2);addBoard.run(id,qid,c,d,finalized?'completed':'unopened',finalized?new Date().toISOString():null,finalized?new Date().toISOString():null,finalized?'completed':null);if(completed&&result.changes)db.prepare('UPDATE questions SET used_count=used_count+1,used=1,date_last_used=date(\'now\'),episode_last_used=? WHERE id=?').run(id,qid)}}
 const addP=db.prepare('INSERT OR IGNORE INTO episode_participants(id,episode_id,display_name,color,score,placement) VALUES(?,?,?,?,?,?)');addP.run('DEMO-P-RUN-1','DEMO-EP-RUN','Ada','#7c3aed',200,null);addP.run('DEMO-P-RUN-2','DEMO-EP-RUN','Linus','#0284c7',100,null);addP.run('DEMO-P-COMP-1','DEMO-EP-COMPLETE','Ada','#7c3aed',1200,1);addP.run('DEMO-P-COMP-2','DEMO-EP-COMPLETE','Linus','#0284c7',900,2);const addAction=db.prepare('INSERT OR IGNORE INTO game_actions(id,episode_id,action_type,participant_id,point_delta,reason) VALUES(?,?,?,?,?,?)');addAction.run('DEMO-A-RUN-START','DEMO-EP-RUN','episode_started',null,0,'Demonstration history');addAction.run('DEMO-A-RUN-SCORE','DEMO-EP-RUN','score_awarded','DEMO-P-RUN-1',200,'Demonstration history');addAction.run('DEMO-A-COMPLETE','DEMO-EP-COMPLETE','episode_completed',null,0,'Demonstration history');
 db.exec('COMMIT'); } catch(error) { db.exec('ROLLBACK'); throw error; }
console.log('Seed complete: 60 labeled sample questions and 4 demonstration episodes available.'); db.close();
